ezsystems/ezplatform

INSTALL.md

There is a wrong command on INSTALL.md. Just replacing ezpublish-community by ezplatform

Fix install command line

---

ezpublish/config/config.yml
ezpublish/config/parameters.yml.dist

ping: @vidarl please test this

EZP-24121: database_port setting in parameters.yml is ignored

---

doc/nginx/etc/nginx/sites-available/mysite.com

See: http://nginx.org/en/docs/http/ngx_http_core_module.html#client_max_body_size
Ran into this issue while trying to upload a big file on the Platform UI
Manual test

Nginx : Allow to configure upload max size

---

composer.json
ezpublish/EzPublishKernel.php

Link to Jira task: https://jira.ez.no/browse/EZP-24150
More info: https://github.com/ezsystems/DemoBundle/pull/149

EZP-24150: Implement privacy cookie law in demo bundle

---

doc/apache2/vhost.template

JIRA: https://jira.ez.no/browse/EZP-24313
See also https://github.com/ezsystems/ezpublish-community/pull/241

Fix EZP-24313: Assets for dev environment being served from disk in Apache

---

INSTALL.md

See ezsystems/ezpublish-community/pull/183

EZP-23339: use correct 'xargs sudo chmod' order

---

ezpublish/EzPublishKernel.php

See ~~https://github.com/ezsystems/ezpublish-community/pull/172~~ [ezpublish-community/pull/243](https://github.com/ezsystems/ezpublish-community/pull/243)

Use global namespaces in EzPublishKernel

---

.gitignore
composer.lock

see: https://github.com/ezsystems/ezpublish-kernel/pull/1308
Update to github auth cherry picked to master already to see if it was enough to get it running. (*Update: it was not, this is more and more clearly an issue with packagist, and not github, this PR fixes that tough*)

[Travis] Get Travis to run again

---

INSTALL.md

https://jira.ez.no/browse/EZP-24579
This PR only update the INSTALL.md to go with https://github.com/ezsystems/PlatformUIBundle/pull/283

EZP-24579 updating INSTALL.md with the new url to call the application

---

.gitignore
.php_cs
bin/ezrouter.php
ezpublish/EzPublishCache.php
ezpublish/EzPublishKernel.php
ezpublish/autoload.php
web/index.php

> https://jira.ez.no/browse/EZP-24612

EZP-24612: Switch to PSR-2

---

INSTALL.md
composer.json
ezpublish/EzPublishKernel.php
ezpublish/config/config.yml
ezpublish/config/ezpublish.yml.example
ezpublish/config/parameters.yml.dist

https://jira.ez.no/browse/EZP-24745
review ping @pspanja @bdunogier @lolautruche 
Todo:
- Bugs encountered:

EZP-24745: Make SolrBundle ready for release

---

behat.yml.dist

PlatformUI Behat profile and suites needed to run the BDD tests

Add platformUI profile and suite to behat.yml

---

behat.yml.dist
ezpublish/EzPublishKernel.php

> Story: [EZP-24774](https://jira.ez.no/browse/EZP-24774)
Adds a `core` profile with a `console` suite to `behat.yml.dist`.

BDD: Test Console siteaccess

---

ezpublish/config/config.yml
ezpublish/config/config_dev.yml
ezpublish/config/config_prod.yml
ezpublish/config/default_parameters.yml
ezpublish/config/parameters.yml.dist

Log settings in parameters

---

.travis.yml
behat.yml.dist
bin/.travis/configure_apache2.sh
bin/.travis/generatevhost.php
bin/.travis/prepare_ezpublish.sh
doc/apache2/vhost.template
ezpublish/config/config_behat.yml

See https://github.com/ezsystems/ezpublish-kernel/pull/1425

Helper branch for EZP-24869

---

GETTING_STARTED.md
INSTALL.md
README.md
behat.yml.dist
doc/apache2/vhost.template
doc/nginx/etc/nginx/ez_params.d/5.3_cluster/ez_cluster_rewrite_params
doc/nginx/etc/nginx/ez_params.d/ez_cluster_rewrite_params
doc/nginx/etc/nginx/ez_params.d/ez_rewrite_params
doc/nginx/etc/nginx/sites-available/mysite.com

Now pointing to ezpublish-community and eZ Publish Platform 5.x for legacy needs,
same will be done in doc and everywhere to make it possible to learn platform
w/o known anything about legacy.
review ping @bdunogier @lolautruche

Cleanup repo as preperation for release

---

app/AppKernel.php

Fixes class name in license header.

EZP-25100: Fix class name in AppKernel.php after #70

---

README.md

Added description based on Slack conversation: https://ezcommunity.slack.com/archives/ezplatform-use/p1450429296001006

Added info about eZ Platform Demo

---

README.md
RUNNING_BEHAT.md

I had to run behat to troubleshoot an issue. While it was running, I wrote a bit of doc on how to run it.
It avoids asking around (for basics at least) and/or look in `.travis.yml`
I know it is not complete, but it is meant to be a first step.

Basic doc on running behat

---

bin/vhost.sh
doc/apache2/vhost.template
doc/nginx/vhost.template

- Renamed applicable template variables that SYMFONY_
- Reorder/grouped related options
- Fixed bug : BODY_SIZE_LIMIT was not calculated before injected into template

Improve bash vhost script

---

app/config/ezplatform.yml

https://jira.ez.no/browse/EZP-25369

Improve EZP-25369: Remove configuration from installers

---

INSTALL.md
bin/.travis/prepare_ezpublish.sh

Just small update now to align with symfony 2.8.
~~~Background: Recent discussions with dpobel on permissions, and PM request to make recording of install process made me think we should simplify directory permissions greatly, by using a script we can theoretically make it more predictable and less error prone. dpobel I didn't remember what you were voicing as your preference on this, I think it was making sure both command line and www user has rights but others have limited rights.~~~

Small update to directory permissions to align with Sf 2.8

---

app/config/routing.yml
behat.yml.dist

> Required by https://github.com/ezsystems/repository-forms/pull/67

UGC routes + BDD

---

bin/.travis/configure_mysql.sh
bin/.travis/disable_xdebug.sh
bin/.travis/ezrouter.php
bin/.travis/prepare_ezpublish.sh
bin/.travis/prepare_selenium2.sh
bin/.travis/prepare_system.sh
bin/.travis/router_behat.php
bin/.travis/setup_from_external_repo.sh

Needed by https://github.com/ezsystems/PlatformUIBundle/pull/524

Router behat + reorganized .travis shell scripts

---

doc/apache2/vhost.template
doc/nginx/ez_params.d/ez_rewrite_params

Adopt convention from ezplatform-demo.
Issue: https://jira.ez.no/browse/EZP-25635

EZP-25635: Added rewrite rule for assets folder

---

bin/vhost.sh

Fixes for vhost.sh
This is based on AR's travis-docker branch and I use the same concepts.
Changes:
- Removes "if[var...]" in output ( lines remains ordinary comments without our "if" statement
- Fixed "#if[VAR!=some-other-value] " code so it now works with multiple occurences

[vhost.sh] Fixed conditional commented lines

---

app/AppKernel.php
app/config/routing.yml
composer.json

> Implement https://jira.ez.no/browse/EZP-25653
> Status: Ready for review
> PlatformUI PR: https://github.com/ezsystems/PlatformUIBundle/pull/545
Adds eZSupportTools to app kernel, main routing, and requirements. Require dev branch of platform-ui-bundle.

Fix EZP-25653: Use eZSupportTools in PlatformUI

---

composer.json

https://jira.ez.no/browse/EZP-25915
ref https://github.com/ezsystems/ezpublish-kernel/pull/1684

EZP-25915: Avoid RunTimeException on composer update/install

---

app/config/default_parameters.yml
app/config/parameters.yml.dist
composer.json

https://jira.ez.no/browse/EZP-25974
To simplify install, move parameters that aren't so common to setup on first install to default parameters file.

EZP-25974: Reduce parameters user is asked about on install

---

.travis.yml
doc/docker-compose/README.md

Redis doc and testing on travis

---

app/config/parameters.yml.dist

jira issue: https://jira.ez.no/browse/EZP-26287
Form SensioLabsInsight:
> Symfony secret should be changed
> The secret is the default one from the Symfony Standard Edition

[Insight] Symfony secret should be changed

---

doc/docker-compose/install.yml

jira issue: https://jira.ez.no/browse/EZP-26286
Tested on SensioLabsInsight.
@andrerom could you please test it with your install process?

[Insight] YAML files should not contain syntax error

---

README.md

just updating links that are outdated

small update on the readme

---

app/AppKernel.php
composer.json

As needed by https://github.com/ezsystems/PlatformUIBundle/pull/525

[Composer] Add BazingaJsTranslationBundle

---

composer.json

[composer] Update ezsystems/content-on-the-fly-prototype to version 0.1.7

---

composer.json

- correct outdated php requriment
- make script section reuse each other to get rid of the duplication
- add `@composer dump-autoload --optimize` to post-create-project as `create-project` command does not support specifying this using argument, unlike `install` and `update`

Correct PHP version and additional composer .json improvements

---

.dockerignore
.env
.travis.yml
Dockerfile
doc/docker-compose/README.md

images:
- update PHP to 7.1
- update MariaDB to 10.1
- Selenium 3.0
other stuff:
- update some docs
- don't ignore .git folders in vendor dirs, composer needs them when working with dev packages

Update docker images

---

bin/.travis/trusty/setup_from_external_repo.sh

Adjust setup_from_external_repo.sh in ezplatform meta
https://jira.ez.no/browse/EZS-1281

EZS-1281: Adjust setup_from_external_repo.sh

---

composer.json

> [EZP-26829](https://jira.ez.no/browse/EZP-26829)
> Related to https://github.com/ezsystems/PlatformUIBundle/pull/773 and https://github.com/ezsystems/ezpublish-kernel/pull/1889
Required by in-context translation.

Added ach-UG translation to the requirements

---

doc/i18n/in_context_translation.md

After adding this content to our Documentation on doc.ez.no, the Doc Squad did a Review and some changes were made in the text.
@DominikaK @kusztel

Changes according to the Doc Review EZP-26889

---

doc/i18n/distribute_translations.md
doc/i18n/handle_translation_in_contribution.md
doc/i18n/in_context_translation.md
doc/i18n/install_translation_package.md
doc/i18n/integrate_new_string_to_translate.md
doc/i18n/translation_workflow.md

Comments to translation doc moved to pull request, as requested.

Some language fixes

---

.env
.travis.yml
Dockerfile
bin/.travis/trusty/update_docker.sh
doc/docker-compose/Dockerfile-solr
doc/docker-compose/README.md
doc/docker-compose/base-dev.yml
doc/docker-compose/base-prod.yml
doc/docker-compose/blackfire.yml
doc/docker-compose/install.yml
doc/docker-compose/redis.yml
doc/docker-compose/selenium.yml
doc/docker-compose/solr.yml

Cherry-picked bug fixes and minor improvements from other PR's, should still pass on travis.

Some minor Docker fixes for 1.10

---

app/AppKernel.php
app/config/config.yml
app/config/routing.yml
composer.json

Integrates [ezsystems/hybrid-platform-ui](http://github.com/ezsystems/hybrid-platform-ui) into ezplatform.

[WIP] Hybrid ui integration

---

.gitignore
app/AppKernel.php
app/config/ezplatform_behat.yml
composer.json

> https://jira.ez.no/browse/EZP-27454

Fix EZP-27454: Add the ez-design-engine to ezplatform by default

---

doc/docker/Dockerfile-varnish

As of v2 xkey will be default so adding it here also to take advantage of it in v2 work.

[Docker] Compile in varnish-modules for optional xkey usage

---

bin/vhost.sh

Came across this file while doing something else, noticed a few typos.

Spelling & grammar corrections in vhost.sh

---

app/AppKernel.php

Added react modules bundle into AppKernel.

Added react modules bundle into AppKernel

---

app/config/config_behat.yml
behat.yml.dist
composer.json

> JIRA: https://jira.ez.no/browse/EZP-28018
Corresponding PR with tests: https://github.com/ezsystems/ezplatform/pull/223
Adding basic Behat configuration for v2 and composer packages.

EZP-28018: Add Behat dependencies and configuration

---

app/AppKernel.php
composer.json

Add WhiteOctoberPagerfantaBundle to implement pagination feature in new Admin UI

Add WhiteOctoberPagerfantaBundle

---

app/config/config.yml
composer.json

**Jira ticket:** https://jira.ez.no/browse/EZP-28434

EZP-28434 As a developer, I want to compile sass in assetic

---

doc/varnish/vcl/varnish4_xkey.vcl

Hello,
I am not sure why you removed the `Accept-Encoding` normalization and the `X-Forwarded-For`.
It might be useless to add it, I am not sure, was it on purpose? (I will update the PR if you don't want it)
Also, I have added the `X-Cache-TTL` which is really useful for debugging. As a developper we want to be sure of the TTL we put in Varnish (ie in the Backend Response) and with the new "adjustment" (which is great) the `s-max-age` in the Response is always 600, `X-Cache-TTL` brings back the real TTL information.
Note I have upgraded eZ Launchpad to use `ezplatform-http-cache` by default now with this VCL ;)
Then you can test easily!

Better TTL debug

---

app/config/config.yml

**Jira ticket: https://jira.ez.no/browse/EZP-28511**

EZP-28511: Cannot use assetic:watch

---

.travis.yml
bin/.travis/trusty/setup_ezplatform.sh

Also `[Travis] For now disable testing on varnish`.

[Travis] Use .env file for picking install

---

app/config/default_parameters.yml
app/config/ezplatform.yml
app/config/routing.yml

| Question      | Answer
| ------------- | ---
| Tickets       | N/A
| Bug fix?      | no
| New feature?  | no
| BC breaks?    | no
| Tests pass?   | yes
| Doc needed?   | yes
| License       | [GPL-2.0](https://github.com/ezsystems/ezplatform-admin-ui/blob/master/LICENSE)
Follow up to: https://github.com/ezsystems/ezplatform-admin-ui/pull/184
Both PRs should be merged at the same time.

fix: Add "admin" siteaccess to configuration

---

composer.json

^0.5 does not install anything newer than 0.5.99

Fix Platform Admin UI assets package version

---

doc/docker/distribution.yml

See https://jira.ez.no/browse/EZP-28697 for discussion
If accepted, this one should be merged at least to master, 2.0 and 1.13 branches, and to downstream meta repos

Fix EZP-28697 : Serving web/var/ files via nginx

---

INSTALL.md

Based on @sunpietro suggestion in https://github.com/ezsystems/developer-documentation/pull/139

[INSTALL] Add instructions to clear sessions directory

---

Dockerfile
doc/docker/Dockerfile-distribution

Some minor changes forgotten in 8065c6faf4d7615f413f014b9ac86efb3ffb7cd1

[WIP] Fixed Dockerfiles to work with Symfony 3

---

doc/docker/README.md

Tiny `doc/docker/README.md` nitpick fix.

Fix docker/README.md nitpick

---

doc/docker/README.md
doc/docker/redis-session.yml

Simple example on how to store sessions in a separate redis instance

[Docker] Added redis-session container

---

.gitignore
.platform.app.yaml
.platform/services.yaml
app/config/cache_pool/singlememcached.yml
app/config/cache_pool/singleredis.yml
app/config/dfs/dfs.yml
app/config/env/generic.php
app/config/env/platformsh.php
bin/vhost.sh
doc/apache2/vhost.template
doc/docker/README.md
doc/docker/dfs.yml
doc/docker/redis-session.yml
doc/nginx/ez_params.d/ez_rewrite_dfsimage_params
doc/nginx/ez_params.d/ez_rewrite_image_params
doc/nginx/vhost.template

This PR makes it convenient to config cluster settings when using docker or platform.sh
by cluster config I mean:
- session stored in redis
- cache stored in redis
- enabling dfs file handler

EZP-28844: Fix cluster support in docker and Platform.sh

---

app/config/config.yml
app/config/default_parameters.yml
app/config/env/platformsh.php

This one depends on https://github.com/ezsystems/ezpublish-kernel/pull/2245
See the [Jira ticket](https://jira.ez.no/browse/EZP-28800) for further info

EZP-28800 : Make it possible to store session in redis when using platform.sh

---

.travis.yml
bin/.travis/trusty/setup_from_external_repo.sh
bin/.travis/trusty/update_docker.sh
doc/docker/install.yml

Also see if this might fix varnish segmentation fault also.
*NB: This is Stuck! Ideally should report this to [travis](https://github.com/travis-ci/travis-ci/issues/8870), however I have unsuccessfully been stuck at segmentation fault before so any kind of report will need a reproducible case for them to look into it...*

[Docker/Travis] Retry composer install on issues & update docker-compose

---

.platform.app.yaml

The diff says it all I guess....

Fixed typo

---

app/config/security.yml

Reverts ezsystems/ezplatform#272

Revert "EZP-26238: eZPlatform login screen redirecting to the link the user entered initially"

---

app/config/security.yml

This PR adds the new firewall which is needed to be able to reset user password.

EZP-28792: Reset my forgotten password.

---

.platform.app.yaml
app/AppKernel.php

> Issue: https://jira.ez.no/browse/EZEE-1910

EZEE-1910: [Platform.sh] Speed up deployment when in production to avoid downtime

---

INSTALL.md

See https://github.com/ezsystems/developer-documentation/pull/203

EZP-26809: unifying install instructions

---

composer.json

Updates symfony conflicting version to 3.4.9.

Update symfony conflicting version

---

app/AppKernel.php
composer.json

> JIRA: https://jira.ez.no/browse/EZP-29241

EZP-29241: Add ezsystems/ezplatform-cron to meta repositories

---

app/config/config.yml
composer.json

> JIRA: https://jira.ez.no/browse/EZP-28890
1) Added dumping of javascript translations after composer install/update 
2) Added configuration of extracting translations from `ezsystems/ezplatform-admin-ui-modules`

EZP-28890: Full eZ Platform v2 i18n support

---

.platform.app.yaml
.platform/services.yaml
app/config/env/platformsh.php

This PR adds support for injecting solr config on Platform.sh
TODO:

EZEE-1903: Added solr service template to platform.sh config

---

doc/apache2/Readme.md
doc/apache2/vhost.2.2.template
doc/apache2/vhost.template
doc/nginx/Readme.md
doc/nginx/ez_params.d/ez_prod_rewrite_params
doc/nginx/vhost.template

This PR fixes path to Symfony's console stated  in the comment in Apache vhost template.

Changed console path in assetic comment

---

app/config/config.yml

Jira: [https://jira.ez.no/browse/EZP-29748](https://jira.ez.no/browse/EZP-29748)
reference to: [https://github.com/ezsystems/ezplatform-admin-ui/pull/701](https://github.com/ezsystems/ezplatform-admin-ui/pull/701) and [https://github.com/ezsystems/repository-forms/pull/259](https://github.com/ezsystems/repository-forms/pull/259)

EZP-29748: Replacing the outdated verbiage of eZ Publish from eZ Platform when adding a Policy

---

app/config/routing.yml

> JIRA: https://jira.ez.no/browse/EZP-29933
related PR: https://github.com/ezsystems/ezplatform-admin-ui/pull/771

EZP-29933: Admin UI REST API listener considers 3rd party routes as REST routes

---

doc/docker/selenium.yml

Egzample - [travis build](https://travis-ci.com/ezsystems/ezplatform-page-builder/jobs/172216914) - line 4381.
After verification on the occasion of the tests of [EZP-29419](https://jira.ez.no/browse/EZP-29419), it appears that this will help us.

Increase shared memory size to avoid problems with chrome session

---

app/AppKernel.php
app/config/routing.yml
composer.json

>JIRA: https://jira.ez.no/browse/EZP-29140

EZP-29140: User bundle

---

.env
.platform.app.yaml
doc/docker/Dockerfile-app
doc/docker/Dockerfile-nginx
doc/docker/selenium.yml

For the upcoming 2.5LTS testing, switch to PHP 7.3 as it also enters recommended versions on doc.

[Docker / Platform.sh] Switch to PHP 7.3 for more speed

---

app/AppKernel.php
app/config/routing.yml
app/config/routing_dev.yml
composer.json

> JIRA: https://jira.ez.no/browse/EZP-30208
I opted for automatic installation of GraphiQL (nice UI for testing GraphQL queries) in `dev` environment.

EZP-30208: Add ezsystems/ezplatform-graphql to meta repositories

---

app/AppKernel.php
composer.json

JIRA: https://jira.ez.no/browse/EZP-26686
Enable eZ Matrix bundle. Feature has own repository (PR: https://github.com/ezsystems/ezplatform-matrix-fieldtype/pull/1)

EZP-26686: Add eZ Matrix Field Type to the Platform as a supported bundle

---

doc/apache2/vhost.template
doc/nginx/vhost.template

Add gzip encoding by default Apache & Nginx config 

---

ez.webpack.config.js
webpack.config.js

**Jira ticket:** https://jira.ez.no/browse/EZP-30345
**Requires:** https://github.com/ezsystems/ezplatform-core/pull/3
**Example usage:** https://github.com/ezsystems/ezplatform-matrix-fieldtype/pull/10

EZP-30345: Cannot override webpack encore JS/CSS from bundle

---

app/config/ezplatform.yml

> JIRA: https://jira.ez.no/browse/EZP-30363
> Requires: https://github.com/ezsystems/ezplatform-admin-ui/pull/928

EZP-30363: Provide default Content Tree configuration in meta repositories

---

.platform.app.yaml
app/config/env/platformsh.php

Thanks @andrerom for the fix.
jira ticket: https://jira.ez.no/browse/EZP-30370

[platform.sh] configure purge to local during the deploy phase

---

.gitignore
ez.webpack.custom.configs.js
webpack.config.js

**Jira ticket:** https://jira.ez.no/browse/EZP-30406
**Requires:** https://github.com/ezsystems/ezplatform-core/pull/6

EZP-30406: Cannot add custom webpack config from bundle

---

.travis.yml
behat.yml.dist
bin/.travis/get_behat_features.sh
composer.json

This PR introduces changes that load Fastest extension for behat multithreading.
Ticket: [EZP-30098](https://jira.ez.no/browse/EZP-30098)
Related PRs:
https://github.com/ezsystems/ezplatform-admin-ui/pull/812
https://github.com/ezsystems/ezplatform-page-builder/pull/305
https://github.com/ezsystems/ezplatform-form-builder/pull/138

EZP-30098 [Travis] Implement solution for running tests in threads based on fastest

---

.travis.yml
bin/.travis/get_behat_features.sh

https://jira.ez.no/browse/EZP-30098

Ezp 30098 config fix

---

.travis.yml
bin/.travis/get_behat_features.sh

https://jira.ez.no/browse/EZP-30098

EZP-30098 feature sort script improvement

---

bin/.ci/make_tag.sh
bin/.ci/prepare_archive.sh

Command for tagging the meta repo. Checks that various conditions and safeguards are met, and makes the tag if successful. Does not push the tag.

Make tag command

---

app/config/ezplatform_behat.yml

https://jira.ez.no/browse/EZP-30098

EZP-30098 extends notification timeout for behat env

---

.travis.yml
behat.yml.dist

JIRA: https://jira.ez.no/browse/EZP-29858
Adjusting BehatBundle suites path after changes from https://github.com/ezsystems/BehatBundle/pull/76
Also, removing the BehatBundle job from metarepo, as it doesn't really belong here anymore.

EZP-29858: Adjust Behat suites

---

app/AppKernel.php
app/config/routing_behat.yml
behat.yml.dist

JIRA: https://jira.ez.no/browse/EZP-30539
Adjusting metarepository for changes in:
https://github.com/ezsystems/ezpublish-kernel/pull/2642
https://github.com/ezsystems/BehatBundle/pull/83
Tests failing because of missing Kernel dependency, the same test suite is passing in Kernel PR.

EZP-30539: Move Platform Behat Bundle to BehatBundle

---

app/AppKernel.php
app/config/routing.yml
behat.yml.dist
composer.json

> JIRA: https://jira.ez.no/browse/EZP-28034
REST bundle and Server were extracted from ezpublish-kernel into a separate [`ezsystems/ezplatform-rest`](https://github.com/ezsystems/ezplatform-rest) package and dropped from Kernel via ezsystems/ezpublish-kernel#2630

EZP-28034: Enabled eZ Platform REST bundle

---

.env

> JIRA: https://jira.ez.no/browse/EZP-30644

EZP-30644: Duplicated database configuration in .env

---

composer.json
config/bundles.php

> JIRA: https://jira.ez.no/browse/EZP-30655

EZP-30655: Package ezsystems/ezplatform-cron is missing from OSS

---

composer.json
config/bundles.php

> JIRA: https://jira.ez.no/browse/EZP-30657

EZP-30657: Upgrade `ezsystems/ezplatform-matrix-fieldtype` to use Symfony 4 components

---

doc/apache2/Readme.md
doc/apache2/vhost.template
doc/nginx/Readme.md

https://github.com/ezsystems/ezplatform/commit/7750b01119c984972b2dd8a86bfedf20da86600b was not complete in doc, this completes the move from app.php to index.php, and from web/ to public/
For master only.

Change app.php > index.php and web > public in doc

---

app/config/ezplatform.yml

| Question      | Answer
| ------------- | ---
| Tickets       | https://jira.ez.no/browse/EZP-30695
| Bug fix?      |no
| New feature?  | yes
| BC breaks?    |no
| Tests pass?   | yes
| Doc needed?   | yes
| License       | [GPL-2.0](https://github.com/ezsystems/ezplatform-admin-ui/blob/master/LICENSE)
Related PR:
- https://github.com/ezsystems/ezplatform-admin-ui/pull/1024

EZP-30695: Configured subtree paths for AdminUI

---

.env
config/packages/ezplatform_solr.yaml

> JIRA: https://jira.ez.no/browse/EZP-30693
Complementary pull request to https://github.com/ezsystems/ezplatform-solr-search-engine/pull/143 so SOLR can be now used without issues.

EZP-30693: Enabled SOLR Search Engine configuration

---

.env

> JIRA: https://jira.ez.no/browse/EZP-30667

EZP-30667: eZ Platform 3.0 does not support PostgreSQL setup

---

behat.yml.dist

JIRA: https://jira.ez.no/browse/EZP-30662
Related PRs:
https://github.com/ezsystems/BehatBundle/pull/89
https://github.com/ezsystems/ezplatform-http-cache/pull/95
Adding a Behat suite from http-cache bundle

EZP-30662: Added http cache tests

---

config/packages/behat/ezplatform.yaml

related to : https://github.com/ezsystems/ezplatform-admin-ui/pull/1047

EZP-30809: changed notification timeout for behat

---

.platform.app.yaml
package.json

[platform.sh]Fix for node version
https://jira.ez.no/browse/EZP-30915

EZP-30915: [platform.sh]Fix for node version

---

.platform.app.yaml
composer.json

Added graphql schema generator for installer and p.sh shared directory for graphql schema

GraphQL schema generator in installer + p.sh directory

---

.platform/varnish.vcl

Enable Gzip for a specified content type in Varnish

[Platform.sh] Varnish Comperssion

---

composer.json

> JIRA: -
Changed `ezsystems/ezplatform-solr-search-engine` dependency from `^2.0@dev` to  `^3.0@dev`

Updated ezsystems/ezplatform-solr-search-engine dependency

---

doc/docker/install_script.sh

Fixes:
- Removed superfluous ; and indenting ifs in install_script.sh
- Fixed so that install_script.sh exits properly if composer install fails

Fix install script.sh

---

doc/docker/install_script.sh

#464 had so many conflicts with master I'm opening PR to make sure travis agrees and so @vidarl can check if his change intentions are in place here.
As far as I know I did two modifications to the changes, `fi;` on last if and splitting `php bin/console $APP_CMD` on it's own line as well.

464 master merge for testing and review

---

app/config/config.yml

I added a specific comment to that line to express what issue might be caused by lacking it during migration (401 on REST and AdminUI calls).

Added comment to `ezpublish_rest.csrf_token_intention` to avoid authentication issues

---

config/packages/security.yaml

Related to https://github.com/ezsystems/ezpublish-kernel/pull/2793

EZP-30985: Added eZ user checker to security config

---

doc/docker/selenium.yml

Selenium - added port for vnc and disabled password

Selenium - vnc port

---

behat.yml.dist
doc/docker/README.md
doc/docker/multihost.yml

https://jira.ez.no/browse/EZP-29112

EZP-29112: Implemented scenarios for Site Access matching

---

.env
config/packages/cache_pool/cache.memcached.yaml
config/packages/cache_pool/cache.redis.yaml
config/packages/cache_pool/cache.tagaware.filesystem.yaml
config/packages/ezplatform.yaml

> JIRA: https://jira.ez.no/browse/EZP-30836

EZP-30836: Changed default cache adapter to filesystem based

---

app/config/config_dev.yml
app/config/config_prod.yml

Issue: https://jira.ez.no/browse/EZP-31239
This has been suggested by several partners as safe defaults, but specifically also [netgen/media-site](https://github.com/netgen/media-site)  which they use to bootstrap new project.

EZP-31239: [DX] Reduce amount of generated debug data / dev overhead by default

---

composer.json
config/bundles.php
config/routes/ezplatform_query_field_type.yaml

> [EZP-30924](https://jira.ez.no/browse/EZP-30924)

Added ezsystems/ezplatform-query-fieldtype

---

README.md

Updating the `readme.md` file.
@alongosz Please, perform the merge once the PR is approved by everyone.

[Doc] Updated 'README.md'

---

.platform.app.yaml

Update .platform.app.yaml - set php memory limit

Update .platform.app.yaml - set php memory limit

---

bin/.travis/trigger_regression_build.sh

JIRA: https://jira.ez.no/browse/EZP-31346
Requires script from https://github.com/ezsystems/BehatBundle/pull/127 to be merged first. - done!
Adding a Composer script so that regression build can be triggered by running: ` bin/.travis/trigger_regression_build.sh`.

EZP-31346: [Travis] Added script invoking script triggering regression build

---

config/services.yaml

> JIRA: https://jira.ez.no/browse/EZP-31483

EZP-31483: Removed JMS Translation command service definitions

---

doc/docker/varnish.yml

Adjusting Docker setup after changes made in https://github.com/ezsystems/ezplatform-http-cache/pull/120
Rest job failure unrelated.

[Docker] Changed purge type to "varnish"

---

config/packages/ezplatform.yaml
config/routes/ezplatform_http_cache.yaml

https://jira.ez.no/browse/EZP-31498
Main PR:
https://github.com/ezsystems/ezplatform-http-cache/pull/122

EZP-31498: Restored varnish auth by token

---

composer.json
config/bundles.php
config/packages/ezplatform_admin_ui_modules.yaml

**Jira ticket:** https://jira.ez.no/browse/EZP-31414
**Required PRs:**
https://github.com/ezsystems/date-based-publisher/pull/169
https://github.com/ezsystems/ez-support-tools/pull/48
https://github.com/ezsystems/ezplatform-admin-ui/pull/1314
https://github.com/ezsystems/ezplatform-calendar/pull/54
https://github.com/ezsystems/ezplatform-form-builder/pull/221
https://github.com/ezsystems/ezplatform-graphql/pull/80
https://github.com/ezsystems/ezplatform-matrix-fieldtype/pull/35
https://github.com/ezsystems/ezplatform-page-builder/pull/552
https://github.com/ezsystems/ezplatform-query-fieldtype/pull/31
https://github.com/ezsystems/ezplatform-site-factory/pull/48
https://github.com/ezsystems/ezplatform-user/pull/66
https://github.com/ezsystems/ezplatform-version-comparison/pull/36 …

EZP-31414: As a Maintainer, I want to remove ezplatform-admin-ui-modules package

---

assets/scss/welcome-page.scss
config/packages/ezplatform.yaml
config/packages/ezplatform_welcome_page.yaml
templates/themes/standard/full/welcome_page.html.twig
templates/themes/standard/pagelayout.html.twig
translations/ezplatform_welcome_page.en.xlf
webpack.config.js

https://jira.ez.no/browse/EZP-31518
Kernel PR: ezsystems/ezplatform-kernel#15

EZP-31518: Implement welcome page

---

composer.json

> JIRA: https://jira.ez.no/browse/EZP-31531

EZP-31531: Used hautelook/templated-uri-bundle instead of our fork

---

upgrade/db/mysql/ezplatform-2.5.latest-to-3.0.0.sql
upgrade/db/postgresql/ezplatform-2.5.latest-to-3.0.0.sql

| Question                                  | Answer
| ---------------------------------------- | ------------------
| **JIRA issue**                          | [EZP-31079](https://jira.ez.no/browse/EZP-31079)
| **Type**                                   | bug
| **Target eZ Platform version** | `v3.0`
| **BC breaks**                          | no
| **Tests pass**                          | yes
| **Doc needed**                       | no

EZP-31079: Provided default value for ezuser login pattern

---

config/packages/doctrine.yaml

Ref https://github.com/doctrine/DoctrineBundle/issues/1065

Fix a deprecation warning in Doctrine ORM

---

assets/scss/welcome-page.scss
templates/themes/standard/full/welcome_page.html.twig

This PR changes a little "welcome page" template, so it fits without scrolling on FullHD monitors (in a maximized window, tested on Firefox & Chrome). 
Also, it makes the footer stick to the bottom on bigger screens.

Changed "welcome page" template and CSS so it fits on HD monitors in fullscreen without scrollbar.

---

.gitignore

https://jira.ez.no/browse/EZP-31540

EZP-31540: GraphQL configs are added to .gitignore

---

.env
.travis.yml
doc/docker/Dockerfile-app
doc/docker/Dockerfile-distribution
doc/docker/Dockerfile-nginx

JIRA: https://jira.ez.no/browse/EZP-31619
**TODO**:

EZP-31619: Add tests running on PHP 7.4

---

README.md

Removes mention of archived https://github.com/ezsystems/ezplatform-demo repository from README.

Remove mention of ezplatform-demo from README

---

config/packages/ezplatform.yaml

Update cache_pool comment in ezplatform.yaml

---

composer.json

[Composer] Lock symfony version to 5.0.x

---

composer.json

Update for behat / mink for symfony5

[Composer] Update for behat / mink for symfony5

---

composer.json

Limiting Symfony version to 5.1.x.

[Composer] Bumped Symfony requirement to ^5.1

---

composer.json
config/bundles.php
config/routes/ezplatform_search.yaml

https://github.com/ezsystems/ezplatform-admin-ui/pull/1400
https://github.com/ezsystems/ezplatform-search/pull/1

EZP-31651: Enabled SearchBundle & routes

---

composer.json

> JIRA: https://jira.ez.no/browse/EZP-31688

EZP-31688: Removed obsolete forked 3rd party packages

---

composer.json
config/packages/doctrine_migrations.yaml

> JIRA: -
Aligned project structure with doctrine/migrations v3.0

Upgraded doctrine/migrations to ^3.0

---

composer.json

> JIRA: -
Default configuration is compatible with >= doctrine/doctrine-migrations-bundle  3.0

Require doctrine/doctrine-migrations-bundle@3.0

---

.travis.yml

JIRA: https://jira.ez.no/browse/EZP-31650
Temporarily disabling Trash test cases for 3.1.
Created ticket for updating those TCs: https://jira.ez.no/browse/EZP-31717

EZP-31650: Temporarily disable Trash test cases

---

config/bundles.php
config/routes/ezplatform_search.yaml

https://github.com/ezsystems/ezplatform-search/pull/6
https://github.com/ezsystems/ezplatform-admin-ui/pull/1428

Moved search bundle to new namespace

---

composer.json

Master is the future 3.2 version and branch-alias should reflect it.

[Composer] Updated branch-alias for master

---

.env
config/packages/ezplatform.yaml

https://jira.ez.no/browse/EZP-31607

EZP-31607: Fixed processing of default value of Varnish invalidate token

---

behat.yml.dist

| Question                                  | Answer
| ---------------------------------------- | ------------------
| **JIRA issue**                          | [EZP-31462](https://jira.ez.no/browse/EZP-31462)
| **Type**                                   | bug
| **Required by**                       | ezsystems/ezplatform-user#75 ezsystems/ezplatform-kernel#99
| **Target eZ Platform version** | `v3.1`
| **BC breaks**                          | no
| **Tests pass**                          | yes
| **Doc needed**                       | no
Add behat suite for ezplatform-user

EZP-31462: Add behat suite for ezplatform-user

---

.platform.app.yaml

Update comment about  about (web|public)/var

.platform.app.yaml: Update comment web→public

---

README.md

This removes old instructions for ezPlatform version 2.

Adjust readme instructions to version 3

---

.env
.gitignore
composer.json
config/bundles.php
config/packages/lexik_jwt_authentication.yaml

Added lexik/jwt-authentication-bundle dependency

---

config/packages/security.yaml

Required by:
- https://github.com/ezsystems/ezplatform-graphql/pull/86
- https://github.com/ezsystems/ezplatform-rest/pull/54

EZP-31875: Added firewall rules for JWT auth

---

behat.yml.dist

For more information see:
Official reference: https://github.com/FriendsOfBehat/SymfonyExtension/blob/master/DOCUMENTATION.md#configuration-reference
https://jira.ez.no/browse/EZP-32039

[Behat] Fixed FOB\SymfonyExtension configuration

---

.env.test
assets/app.js
assets/styles/app.css
behat.yml.dist
config/packages/prod/deprecations.yaml
config/preload.php
config/routes/dev/framework.yaml
config/services_behat.yaml
features/demo.feature
templates/themes/standard/full/welcome_page.html.twig
templates/themes/standard/pagelayout.html.twig
webpack.config.js

> JIRA: -
~**NEED REBASE AFTER #613 MERGE.**~
Aligned meta repository with Symfony recipes output and ensured that starting point files works with product. In summary, user can from now start working on 
\* frontend by editing `assets/app.js` i `assets/styles/app.css` (generated by symfony/webpack-encore-bundle recipe)  
\* BDD by editing `feature/demo.feature` (generated by friends-of-behat/symfony-extension recipe)
immediately after creating project

Aligned meta repository with Symfony recipes output

---

config/bundles.php
config/packages/ezplatform_admin_ui.yaml

> JIRA: https://jira.ez.no/browse/EZP-32096
Adds default configuration used by https://github.com/ezsystems/ezplatform-core/pull/21

EZP-32096: Added icon set configuration for Admin UI

---

composer.json

> JIRA: https://jira.ez.no/browse/EZP-32078

EZP-32078: Bumped ezplatform-admin-ui-assets package version

---

assets/scss/welcome-page.scss

Fixed welcome page background size

---

composer.json
config/packages/ezplatform_admin_ui.yaml

> JIRA: https://issues.ibexa.co/browse/EZP-32164

EZP-32164: Changed default icon set path

---

upgrade/db/mysql/ezplatform-3.2.0-to-3.3.0.sql
upgrade/db/postgresql/ezplatform-3.2.0-to-3.3.0.sql

JIRA: https://issues.ibexa.co/browse/EZP-32220

EZP-32220: Added SQL upgrade tables related to SettingService

---

config/packages/overrides/generic.php
config/packages/overrides/platformsh.php
src/Kernel.php

Reverts ezsystems/ezplatform#626
Original solution did not work well with HTTP Cache. Reverting for now and will provide proper fix soon.

Revert "EZP-32214: Refactored config/packages/overrides/* as Compiler Passes"

---

.platform.app.yaml

[Platform.sh] Update url to env variables for composer

[Platform.sh] Update .platform.app.yaml

---

templates/themes/standard/full/welcome_page.html.twig

This PR provides fixed links contained ezplatform.com domain.

Fixed documentation links on welcome page

---

upgrade/db/mysql/ezplatform-3.2.3-to-3.2.4.sql
upgrade/db/postgresql/ezplatform-3.2.3-to-3.2.4.sql

Related to: https://github.com/ezsystems/ezplatform-kernel/pull/162

EZEE-3453: Added SQL update scripts

---

composer.json

The branch `v3.2-to-v3.3-upgrade` should be merged when doing a version upgrade to make the transition from v3.2 (metarepository installation) to v3.3 (flex project) easier.
It contains:
1) Composer.json from ibexa/website-skeleton (https://github.com/ibexa/website-skeleton/blob/main/composer.json) so that our users don't have to apply the changes manually.
Related:
https://github.com/ezsystems/ezplatform-ee/pull/188
https://github.com/ezsystems/ezcommerce/pull/50

Prepared branch for easier version upgrade

---

.env

JIRA: https://issues.ibexa.co/browse/IBX-406

IBX-406 [Travis] Updated selenium container to 20210422 version.
