ezsystems/ezplatform

INSTALL.md
Hello eZ Platform People!
We recently helped a co-worker who was new to eZ Platform solve an issue that may seem trivial to the more experienced eZ Publish developers. 
In short, it was unclear (at the time) to our friend what upon a new default installation and setup of eZ Platform, the default admin user password was.
Re: http://share.ez.no/forums/ez-publish-5-platform/ez-platform-backend
We've also found that many users, even experienced eZ Publish users are not yet 100% clear as to the real differences between eZ Platform and eZ Publish and as such we find we have to do a fair amount of educating users who often ignore eZ Publish documentation (even on doc.ez.no confluence) because it says eZ Publish instead of eZ Platform.
While we know this will given more time (this is just the …
=> Add default admin password documentation

INSTALL.md
- Specifies that archives are the ones from share.ez.no (as tags don't contain vendors, and are for composer use)
- Also improve & simplify the composer create-project instructions
=> Improve install to clarify archive & composer use

ezpublish/EzPublishKernel.php, ezpublish/config/ezpublish.yml.example
This PR resolves https://jira.ez.no/browse/EZP-23471
`ezsystems/ezpublish-kernel` counterpart of https://github.com/ezsystems/ezpublish-kernel/pull/1210.
=> Implement EZP-23471: semantic configuration for search engines

bin/.travis/prepare_ezpublish.sh, ezpublish/EzPublishKernel.php
Testing if https://github.com/ezsystems/ezpublish-kernel/pull/1244 also can remove need for manual cache clar on travis, hence be tested by behat tests.
*This cleans up some issues that was created when we introduced installer here in terms of having to do custom stuff for behat which with the kernel change here and the one in ezpublish-kernel is no longer needed.*
=> Fix EZP-24158: Need to clear cache manually after platform install

README.md
Hello,
Related issue for these pull requests: https://jira.ez.no/browse/EZP-24311
Per request from Andre to update the repository README.md documentation to clarify the differences between the older ezpublish-community repository and the new ezplatform repository in order to re-start community builds for the 5.x branch we are creating this issue.
Goal: Clarify the differences between the older ezpublish-community repository and the new ezplatform repository in repository README.md documentation.
To achieve this goal we will update the README.md documentation in each repository via separate pull requests to explain the main difference (today) between each repository is the inclusion or exclusion of legacy dependencies by default.
This pull request addresses the issue in question for this …
=> Fix EZP-24311: Clarify the differences between ezpublish-community and ezplatform repositories in README.md documentation

doc/apache2/vhost.template, doc/nginx/etc/nginx/ez_params.d/ez_rewrite_params
> Identical to ezsystems/ezpublish-community#242
Removes the legacy rewrite rules for REST API v1, as it needs to go through the new stack to clear new stack cache.
=> EZP-24278: removed legacy rewrite rule for REST API v1

.gitignore, .travis.yml, behat.yml.dist
See https://github.com/ezsystems/ezpublish-community/pull/207
=> Move behat.yml to behat.yml.dist

behat.yml.dist
This PR exposes in behat.yml.dist the setting for specifying host where selenium is running
=> Added wd_host setting for the Selenium2 driver

behat.yml.dist, composer.json
This PR makes it possible to export results of behat tests in jUnit format, which is applicable when running tests from for instance jenkins.
Unfortunately, the jarnaiz/behat-junit-formatter do not deal with scenarios which contains undefined sentences ( which currently happen to exists our behat tests ). Thus, the custom package  repository...
=> Added behat-junit-formatter dependency to composer.json

behat.yml.dist
Tests for Platform UI uncovered that "build/tests" is a non existing and non writable folder out of the box, so changing it to use a writable one (ezpublish/logs/junit) to avoid issues with this.
/cc @vidarl
=> Make Behat JUnitFormatter use writable folder

INSTALL.md
JIRA: https://jira.ez.no/browse/EZP-24796
Add some additional information for using `chmod` when setting up eZ Publish.
Even though not ideal, the added notes provide additional info and general "guidelines" for this method.
ping @andrerom @bdunogier @lolautruche
=> EZP-24796: update INSTALL doc with additional info for using chmod

bin/.travis/setup_from_external_repo.sh
This makes it possible to pass multiple packages requirements to `setup_from_external_repo.sh`:
```
php bin/.travis/setup_from_external_repo.sh /dir foo/a:v1.2.3 bar/b:v2.3.4
```
=> Allow multiple deps update in behat setup

behat.yml.dist
> Related pull-requests: https://github.com/ezsystems/ezpublish-kernel/pull/1464, https://github.com/ezsystems/DemoBundle/pull/187, https://github.com/ezsystems/PlatformUIBundle/pull/378.
This moves profiles and suites away `behat.yml.dist` to the bundle they actually cover.
It allows any PR author to update the behat suites / contexts for a PR on any of the covered bundles without creating another PR to ezplatform.
The REST one contains a configuration bonus.
=> BDD: Moved core/rest configs to imports

ezpublish/config/config_behat.yml, ezpublish/config/routing_behat.yml
In `behat` env, the routing.yml file from `@EzSystemsPlatformBehatBundle` is loaded. It contains routes used in behat scenarii.
The (empty) file has already been merged into ezpublish-kernel@master.
=> BDD: Added behat routing file + BehatBundle routes

ezpublish/EzPublishKernel.php
This PR resolves https://jira.ez.no/browse/EZP-24915
Corresponding PRs:
* https://github.com/ezsystems/ezplatform-solr-search-engine/pull/24
* ezsystems/ezpublish-kernel#1452
* https://github.com/ezsystems/ezpublish-platform/pull/18
* https://github.com/ezsystems/ezpublish-community/pull/250
This updates `EzPublishKernel.php` for the changed namespace of the Solr Search Engine bundle.
=> Fix EZP-24915: Solr Search Engine repository structure cleanup

composer.json, ezpublish/EzPublishKernel.php
This PR resolves https://jira.ez.no/browse/EZP-24925
This adds `ezsystems/ezplatform-xmltext-fieldtype` to `composer.json` and registers its bundle with kernel.
=> Implement EZP-24925: Extract XmlText field type out of kernel into separate repository

bin/.travis/prepare_ezpublish.sh, composer.json, ezpublish/config/config.yml
replaces / closes #66 
Should speed up things in dev env a bit, in addition to avoiding disk the issue with large disk use by profiler files. Very optimistic, but might be it gets rid of the strange issues some people have with profiler not loading, but that would be just to much of a luck :)
=> Disable Stash cache value tracking by default

app/AppKernel.php, composer.json
> Part of https://jira.ez.no/browse/EZP-24925
Not part of ezplatform by default, but can be installed separately from http://packagist.org/packages/ezsystems/ezplatform-xmltext-fieldtype.
=> Removed xmltext fieldtype

composer.json
eZ Platform is a project/application, not "just" a library… Well, that's a massive PR for once :smile:
=> Set package type to "project"

.gitignore
> https://jira.ez.no/browse/EZP-25314
`app/check.php` and `app/SymfonyRequirements.php` are (re)generated by Symfony when installing/updating vendors, so they're not too useful to be in the repo.
`web/css` and `web/js` folders are also (re)generated when installing/updating vendors, by Assetic.
=> EZP-25314: Add misc Symfony files, web/css and web/js to .gitignore

behat.yml.dist
As discussed in the [travis fix PR](https://github.com/ezsystems/BehatBundle/pull/42) added the missing behat.yml to behat.yml.dist
=> Added missing behatbundle behat.yml to behat.yml.dist

bin/ezrouter.php
> Fixes [EZP-25406](https://jira.ez.no/browse/EZP-25406)
Applies the ezpublish -> app rename to ezrouter.
The internal server runs fine again: `php app/console server:run -r bin/ezrouter.php 0.0.0.0:8080`
=> Fixed internal server / ezrouter.php

behat.yml.dist
This PR configures Behat so it does not fail when a E_ALL and ~E_USER_DEPRECATED php error occur.
=> [Behat] Remove Behat failure on deprecation warnings

.travis.yml
Causes an error on builds, with no specs being found.
See https://travis-ci.org/ezsystems/ezplatform/builds/116877568.
=> [travis] removed -v option from behat command line

app/AppKernel.php, app/config/routing.yml, composer.json
> Fixing issue found in https://jira.ez.no/browse/EZP-25653, PR against https://github.com/ezsystems/ezplatform/pull/104
> See also: ez-support-tools PR: https://github.com/ezsystems/ez-support-tools/pull/16
> Status: Ready for review
The system_info_view route is not used, and has no access control, this removes it.
=> Remove unused system_info_view route

app/config/ezplatform.yml
> Doc fix for https://jira.ez.no/browse/EZP-25638
> Status: Ready for review
In the immortal words of Boromir: "One does not simply remove eng-GB from the site languages list."
=> Fix EZP-25638: Editing content types when default siteaccess only uses nor-NO as language

INSTALL.md
JIRA: https://jira.ez.no/browse/EZP-25595
Just adds a note on the consequence of the hardcoded permission in the version of Flysystem required by eZ Platform.
=> EZP-25595: Added a note on permissions for files created by FlySystem

app/config/config.yml, app/config/env.php, bin/vhost.sh, doc/apache2/vhost.template, doc/nginx/vhost.template
- Adds a `env.php` file to be able to inject parameters from env variables *(opt in, so can't use `SYMFONY__` here as it only works if param is not defined in yml)*
- Adjust `vhost.sh` and `vhost.templat`s to allow skipping undefined env vars *(so a php-fpm container can have them set on container instead of hardcoded in vhost of the httpd contianer, which is inconvinent for restarts of php to change settings)*
These are splitted out from #97 as it will need further work before it is ready.
=> Prepare distribution for container use

behat.yml.dist
Add to behat.yml.dist the [EzBehatExtension](https://github.com/ezsystems/ezpublish-kernel/blob/master/eZ/Bundle/PlatformBehatBundle/ServiceContainer/EzBehatExtension.php) which enables the usage of the [ArgumentResolver](https://github.com/ezsystems/ezpublish-kernel/blob/master/eZ/Bundle/PlatformBehatBundle/Context/Argument/AnnotationArgumentResolver.php) so that we can inject services in Behats contexts see [Accessing eZplatform Kernel Services](https://github.com/ezsystems/ezpublish-kernel/tree/master/doc/behat#accessing-ez-platform--kernel-services)
=> [Behat] Add EzBehatExtension in behat.yml.dist

INSTALL.md
vhost generation command should only have one '\' to break the line.
=> [DOC] Removed extra '\' in INSTALL.md vhost generation command

composer.json
https://jira.ez.no/browse/EZP-25098
This will trigger a whole bunch of deprecation warnings for things removed in 3.0,
and if possible we will aim to take that gradually as soon as we merge this.
See: https://github.com/symfony/symfony/blob/2.8/UPGRADE-2.8.md
=> [Composer] Bump Symfony to 2.8

.env, app/config/cache_pool/singlememcached.yml, app/config/cache_pool/singleredis.yml, app/config/default_parameters.yml, app/config/env.php, app/config/ezplatform.yml, doc/docker-compose/redis.yml
Issue: https://jira.ez.no/browse/EZP-25943
As a step towards cluster setup, adding redis so we can test that.
Memcached can easily be added as well later when it arrives with PHP 7.0 support, assuming we bother *(Symfony 3.x only support Redis, and adding extensions to php image increases it's size)*.
=> EZP-25943: [Docker] Add redis config and way to inject it

app/config/config.yml
JIRA Story: [EZP-26128](https://jira.ez.no/browse/EZP-26128)
This PR removes deprecated code from *ezplatform*. Right now it's only a small change to `config.yml`.
**TODO**:
=> EZP-26128: As a Developer I want deprecation issues resolved, so that application logs are clean

app/config/routing_dev.yml, app/phpunit.xml.dist, behat.yml.dist, composer.json, web/app.php
PR related to the JIRA Story: [EZP-26128](https://jira.ez.no/browse/EZP-26128) and [Kernel PR #1750](https://github.com/ezsystems/ezpublish-kernel/pull/1750).
This PR bumps `sensio/distribution-bundle` to `v5.0` and updates `eZ Platform` according to [this update notes](https://github.com/sensiolabs/SensioDistributionBundle/blob/master/UPGRADE.md).
Please note that:
- We still use `app/cache` and `app/logs` directories, so no changes to `app/AppKernel.php` are needed.
- `app_dev.php` includes `app.php`, so only `app.php` includes now autoloading code.
- `app/console` already includes autoloading code, so no change needed there.
**TODO**:
=> EZP-26128: Align eZ Platform with Sensio Distribution Bundle v5.0

composer.json
Followup to : https://github.com/ezsystems/ezplatform/commit/dfe122b1f386e5d9b70dc6b475038ab0c16a2231#commitcomment-18733964
Legacy bridge requires `sensio/distribution-bundle` 3.x or 4.x and will not be able to install with `^5.0` as a version requirement.
=> Allow sensio/distribution-bundle 3.x, 4.x or 5.x to allow legacy bridge install

.dockerignore, .env, Dockerfile, doc/docker-compose/base-prod.yml
- Reduces image size down to php image +200mb as opposed to +300mb or more
- As .dockerimage is fixed as part of this, layering issues on cache/logs folders might now be completely fixed
Also added check in Dockerfile to verify ignored folders like `.git` is correctly removed as safety measure.
@bdunogier This might be a good time for you to retry on the setup where it did not work last time.
=> Docker improvments 

.env, Dockerfile, doc/docker-compose/selenium.yml
Switch to new [v1 image](https://github.com/ezsystems/docker-php/pull/15) of docker-php which has [entrypoint](https://github.com/ezsystems/docker-php/blob/master/php/scripts/docker-entrypoint.sh#L50-L58) which makes it possible to run custom logic in it on startup without having to extend it. It also contains support for adapting adapting behat.yml so we don't need to hardcode that as container command here.
=> [Docker] Switch to slightly updated format for php image with entrypoint

.env, COPYRIGHT, GETTING_STARTED.md, INSTALL.md, README.md, UPGRADE.md
=> Misc text updates

.env
Selenium 3 causes issue with behat because it uses the new marionette/geckodriver(see https://github.com/mozilla/geckodriver) which are not yet fully implemented. For now the version should be pinned to the previous one
=> Pin selenium docker image version to 2.53.1

doc/nginx/ez_params.d/ez_prod_rewrite_params
fix some typo of nginx rewrite rules
rewrite "^/fonts?/(.*)\.ttf" "/font$1/$2.ttf" break; to rewrite "^/font(s?)/(.*)\.ttf" "/font$1/$2.ttf" break;
=> EZP-26500: fix some typo of nginx rewrite rules

app/AppKernel.php, app/config/routing.yml, composer.json
> Issue: https://jira.ez.no/browse/EZP-26682
To be able to more strongly advice people to use clean for install and upgrade* make sure it has same level of features, given the rewrite to integrate the feature is currently on hold.
This applies to ezstudio as well, and once this is merged it can be naturally merged down there.
*_Doc on Studio says people can use demo for upgrade but that causes issue whenever demo add new demo specific features and people merge that in on upgrade. Note: On studio templates and config for landing pages is missing, so this is most likely the root cause for people using demo on upgrade._
=> EZP-26682: Add Content on the Fly Bundle in clean install

app/AppKernel.php, composer.json
> [EZP-26704](http://jira.ez.no/browse/EZP-26704)
Adds [`jms/translation-bundle`](http://jmsyst.com/bundles/JMSTranslationBundle/master/usage) to the requirements.
This package adds a "description" feature, allowing developers to document the original string next to the source code:
```twig
{{ "title.doctor"|trans|desc("David Tenant") }}
```
```php
/** @Desc David Tenant */
$translator->trans("title.doctor");
```
The text will be used as the source in the XLF file, while the key will be stored as `resname`.
=> EZP-26704: JMS Translation Bundle integration

bin/synchronize-translations.sh, composer.json
Jira : https://jira.ez.no/browse/EZP-26834
This PR adds a script to ease translation synchronisation to ezplatform-i18n
=> EZP-26834: Synchronize translations in ezplatform-i18n

doc/i18n/in_context_translation.md
=> EZP-26869: Documented in-context translation usage

.gitignore
https://jira.ez.no/browse/EZP-26801
We want platinum medal in SensioLabsInsight!  ;-)
```
All user specific files from now on should be kept in the global .gitignore file
located in the user's local environment. To do so you have to inform Git which
files should be excluded globally (for every Git repository).
Here is a short instruction about how to exclude selected files globally:
- create a new .gitignore file in your home folder:
touch ~/.gitignore
- add some exclusions, eg:
/nbproject/
/.idea/
- inform Git where it should start looking for .gitignore file:
git config --global core.excludesfile ~/.gitignore
More details about excluding specific file on your local environment can be found
in the official GitHub article: https://help.github.com/articles/ignoring-files/
```
=> EZP-26801: User specific files should not appear in .gitignore

composer.json
> Part of [EZP-22401](https://jira.ez.no/browse/EZP-22401)
Adds the [ezsystems/ezplatform-http-cache](http://github.com/ezsystems/ezplatform-http-cache) package to the requirements.
The bundle is NOT enabled by default, meaning that the http cache feature is identical to what it was before. When enabled, it will automatically replace the kernel http cache features with its own, including multi-tagging.
=> EZP-22401: Added ezplatform-http-cache package to the requirements

doc/i18n/distribute_translations.md, doc/i18n/handle_translation_in_contribution.md, doc/i18n/in_context_translation.md, doc/i18n/install_translation_package.md, doc/i18n/integrate_new_string_to_translate.md, doc/i18n/translation_workflow.md
Documentation for Jira : https://jira.ez.no/browse/EZP-26834
This documents the translation workflow with crowdin.
Test manually
=> EZP-26834 : document translation workflow with Crowdin

.env, .gitignore, .platform.app.yaml, .platform/routes.yaml, .platform/services.yaml, app/config/config.yml, app/config/env/platformsh.php, doc/platformsh/INSTALL.md, doc/platformsh/README.md
> https://jira.ez.no/browse/EZP-27060
> see also https://jira.ez.no/browse/EZS-1402
> Ready for review
Adds the necessary config files to run eZ Platform on platform.sh. This should also be added in the ezstudio and ezstudio-demo repos, see https://github.com/ezsystems/ezstudio/pull/43. Clustering not yet covered.
Note: The instructions in INSTALL.md are valid *after* this PR is merged. Before, in order to test it, you have to cherry pick the commits in this PR into the master branch of your fork, before attempting to make a platform.sh project out of it.
=> EZP-27060: Add platform.sh config

app/config/security.yml
Link: https://jira.ez.no/browse/EZP-27222
Lots of users are not aware of the current limitation with REST basic auth preventing PlatformUI from working. I added a comment in order to make it more clear.
=> EZP-27222: Add a warning comment enabling basic rest auth

app/AppKernel.php
https://jira.ez.no/browse/EZP-27226
This PR fixes the order of bundles inside the `AppKernel.php` file.
The `MultiFileUploadBundle` extends `PlatformUIBundle` hence it should be placed above the `PlatformUIBundle` in the `$bundles` array. This way we can avoid any unexpected issues with the `MultiFileUploadBundle`.
=> EZP-27226: Move MultiFileUploadBundle above the PlatformUIBundle

app/config/config.yml
In Symony 3.3, `trusted_proxies` config has been removed and results in the following exception:
```
[InvalidArgumentException]                                                   
The "framework.trusted_proxies" configuration key has been removed in Symfony
3.3. Use the Request::setTrustedProxies() method in your front controller instead.
```
=> [Symfony 3.3] Remove trusted_proxies config

app/config/config.yml
In Symfony 2.8/3.x, `csrf_protection` is disabled globally by default.
In order to use CSRF, it's mandatory as of Symfony 3.0 to at least use default values
for `framework.csrf_protection` setting. Otherwise `security.csrf.token_manager` service
won't exist, leading to `ServiceNotFoundException` during container compilation.
=> [Symfony 3] Fix missing csrf_protection setting

bin/synchronize-translations.sh
> Requires https://github.com/ezsystems/hybrid-platform-ui/pull/20
> [EZP-27494](http://jira.ez.no/browse/EZP-27494)
Adds hybrid-platform-ui to the translation sources of `bin/synchronize-translations.sh`.
=> EZP-27494: Added hybrid-platform-ui to the i18n sync script

bin/.travis/parameters.yml, bin/.travis/trusty/setup_from_external_repo.sh
This PR aligns eZ Platform `2.0` setup script for Travis with Symfony 3.x directory structure.
Right now behat [tests on ezpublish-kernel `7.0` fail](https://travis-ci.org/ezsystems/ezpublish-kernel/jobs/253597205#L1162) due to failed attempt to setup eZ Platform clean install. 
These changes should hopefully solve the issue.
**TODO**:
- ~Use `doc/docker-compose/base-prod.yml` for all Travis tasks~ // separate issue
=> [Travis] Update Behat setup to make tests passing

doc/apache2/vhost.template, doc/nginx/ez_params.d/ez_rewrite_params
> JIRA: https://jira.ez.no/browse/EZP-27285
The main propose of this PR is to open discussion about default configuration of URL Rewrite Engine which currently allows access to EZP based websites with direct usage of app.php in URL e.g. 
* http://exemple.com/app.php
* http://example.com/anything/you/want/app.php
Besides of non-loaded assets, it may impact on SEO because of [content duplication](https://support.google.com/webmasters/answer/66359?hl=en).
This PR solves EZP-27286 issue with a 404 "Not found" response. Alternative solution with 301 redirect: https://github.com/ezsystems/ezplatform/pull/193
=> Fix EZP-27285: Prevent access to website with direct usage of app.php in URL (404)

app/config/config.yml, app/config/config_dev.yml, app/config/config_prod.yml, app/config/ezplatform.yml, app/config/routing.yml, app/config/routing_behat.yml, app/config/routing_dev.yml, app/config/security.yml, composer.json, web/app.php
Changes _(from symfony standard)_:
- Don't align yml config entries
- Use ' over " around parameters in yml
- Use PSR-4 autoloading to get rid of blank load rule for possible src files causing file stat calls all the time unless class map is generated
- Added some more inline doc
Also from v2: updated some YML inline eZ Platform doc / links.
Note: Additional goal here is to reduce the 2.0 diff to simplify rebases when needed.
=> Backport some cleanups of config and autoload usage from v2

.env, behat.yml.dist, doc/docker/selenium.yml
> JIRA: [EZEE-1710](https://jira.ez.no/browse/EZEE-1710)
The Firefox version used together with Selenium Server 2.53.1 is no longer able to login to Studio admin panel, so there is a need for upgrade to keep Behat tests running.
My solution is to change the Selenium version to 3.4.0 and the driver to Chrome.
My reasoning is as follows:
- there have been huge changes to Firefox driver between 2.* and 3.* (switching to Marionette etc.). Studio tests rely heavily on drag&drops, which started working only recently (in Selenium 3.5.\*, it failed in 3.4.\* in my experiments). Related Selenium issue: https://github.com/SeleniumHQ/selenium/issues/3693
- unfortunately Mink does not support Selenium 3.5.* yet - TraversableElement::findField method does not find elements (and there are many usages …
=> EZEE-1710 change selenium version

doc/docker/selenium.yml
> JIRA: [EZEE-1710](https://jira.ez.no/browse/EZEE-1710)
I'm testing various SHM sizes to find the lowest one for which the tests are stable, as suggested by Vidar here: https://github.com/ezsystems/ezplatform/pull/203 
Result: 128m is fine for Platform - build was green 10 times in a row.
=> EZEE-1710: Check SHM sizes

composer.json
> Ready for review
Purpose: Prevent accidental require/update to known vulnerabilities.
See https://github.com/Roave/SecurityAdvisories which also explains why `dev-master` is used.
Manual test that a vulnerable package is refused:
```
$ composer require zendframework/zendframework:2.3.1
Your requirements could not be resolved to an installable set of packages.
Problem 1
- zendframework/zendframework 2.3.1 conflicts with roave/security-advisories[dev-master].
```
Manual test that Symfony's security checker does its thing:
```
$ php bin/security-checker security:check composer.lock
Symfony Security Check Report
=============================
// Checked file: /home/gl/git/ezplatform/composer.lock
[OK] No packages have known vulnerabilities.
! [NOTE] This checker can only detect …
```
=> Enable roave/security-advisories

app/config/config.yml, app/config/default_parameters.yml
JIRA issue: https://jira.ez.no/browse/EZP-27885
This PR adds a new entry in `default_parameters.yml` which replaces the hardcoded string `collection1` in `config.yml` in order to allow overriding this value for each instance.
original description:
>I always wondered why `solr_core`, unlike similar settings (`database_name`, `search_engine`, ...), is hardcoded in config.yml by default. 
>
> This simple change retains the default behavior but enables multiple instances of ezplatform on the same server, development machine, etc to use separate solr cores of the same solr endpoint.
>
> (I guess everyone who requires setups like these already changed their config.yml in a similar fashion)
=> EZP-27885: solr core name as parameter

app/AppCache.php, app/AppKernel.php, app/config/config.yml, app/config/default_parameters.yml, app/config/env/docker.php, app/config/ezplatform.yml, doc/docker/Dockerfile-varnish, doc/varnish/varnish.md, doc/varnish/vcl/varnish3_ban.vcl, doc/varnish/vcl/varnish4_ban.vcl, doc/varnish/vcl/varnish4_xkey.vcl
> Story: https://jira.ez.no/browse/EZP-28043
Does:
- Enables `ezplatform-http-cache` bundle for:
- tag based invalidation which is able to more reliably clear all affected cache on changes
- xkey based purging on Varnish; allows soft purge, and unlike BAN it does not slow down under heavy usage
- Performance:
- This allows to increased TTL to 24h _(made possible to increase further via ENV var)_
- Also solves related issues:
- Now drops all non session ID cookies on cacheable requests to avoid users not getting why their install does not cache anything when they enable javascript tracking systems
- Make sure error/redirect responses are cached for a short time _(not for the longer ttl time)_
Followup:
- Start to (re-)enable cache for REST resources that where disabled because of http …
=> EZP-28043: As a Developer I want a HttpCache system by default that is cable of reliably clear affected caches on changes

app/config/env/platformsh.php
- Hardcoded cluster DB name
- Cache settings
- Disabling PHPStormPass (makes impossible to run ezplatform in dev mode on platform.sh)
=> Updated platform.sh settings

.php_cs, web/app_dev.php
This PR introduces alignment of php-cs-fixer config after update to `v2.7.1`
Backported to: **1.7 LTS**
php-cs-fixer config was taken from ezsystems/ezpublish-kernel#2107
**TODO**:
=> [CS] Aligned php-cs-fixer config with changes introduced by v2.7.1

composer.json
Currently `2.0` cannot be installed due to the version constraint on `oneup/flysystem-bundle` in `ezsystems/ezpublish-kernel` which allows to install either `^1.0` or `^2.0`. Composer tends to install lower version which makes installation fail due to the BC break in `symfony/symfony` 3.4.0-BETA1. This PR forces `oneup/flysystem-bundle` installation in version 2.x.
=> [composer] Added oneup/flysystem-bundle dependency

doc/varnish/vcl/varnish4_xkey.vcl
> Issue: https://jira.ez.no/browse/EZP-28126
> Epic: https://jira.ez.no/browse/EZP-27624
Improvement to our VCL in terms of not caching responses in Browser and shared proxy caches by default. And with inline suggestions for those that want to adapt it to be less strict or apply to all responses.
=> EZP-28126: Change default Varnish VCL to not cache user varying content in proxies or browsers

composer.json
`composer.json` on `2.0` branch is is missing `config/bin-dir` value which prevented behat from being installed into `bin/` folder. This change is required in order to run Behat tests on our repositories.
=> [composer] Added config/bin-dir key

doc/varnish/vcl/varnish4_xkey.vcl
> Issue: https://jira.ez.no/browse/EZP-28183
When editing Landing pages @mnocon are getting stale content when viewing it afterwards, which I think is because we on purpose allowed that here for view, only exception was REST routes when used from platform ui. So  given we need to ship with sensible defaults, making sure users with sessions sees the latests changes all over seems like a safer choice* _(editors, forum users, admins, shoppers, ..)_.
\* _Only exception kept here is if backend is not healthy, which should not happen here as we have not configured a [probe](http://varnish-cache.org/trac/wiki/BackendPolling) but left that up to the integrator._
=> EZP-28183: Always refresh stale cache for logged in users

app/config/config.yml, app/config/env/generic.php, doc/docker/my-ez-app-stack.yml, doc/docker/varnish.yml
This PR does the following:
- renames app/config/env/docker.php → app/config/env/generic.php as the file contains no docker specific stuff.
- adds possibility to set purge_type via environment variable HTTPCACHE_PURGE_TYPE
- adds possibility to set recommendation settings via environment variables
Note:
When merging this to ezplatform-ee-demo, please note that the recommencation settings are already in docker.php (generic.php) ... Make sure that code is not duplicated, and that is is located  at the same spot in the file to avoid further merge conflicts.
=> EZP-28336 : app/config/env/docker.php is actually non-docker specific

.travis.yml, doc/docker/install.yml
| Question | Answer |
| ------------ | ---------- |
| **Status** | Ready for review |
| **JIRA issue** | [EZP-27752](https://jira.ez.no/browse/EZP-27752) |
| **Bug fix** | yes |
| **BC break** | no |
| **Target version** | `1.13` |
| **Tests pass** | yes |
This PR fixes running REST functional tests by adding missing new language required by these tests.
**TODO**:
=> EZP-27752: [Travis] Injected ez:behat:create-language command

app/config/cache_pool/cache.memcached.yml, app/config/cache_pool/cache.redis.yml, app/config/config.yml, app/config/config_dev.yml, app/config/config_prod.yml, app/config/default_parameters.yml, app/config/ezplatform.yml
This changes param names back to "human readable" format to keep BC with eZ Platform 1.x, while still allowing for fallback to environment variables or if environment variables do not exist, fallback to values specified with `'%env(ENV_NAME)%'` format.
This is the same what Sylius does with their parameters: https://github.com/Sylius/Sylius/blob/master/app/config/parameters.yml.dist
=> Refactor param names to keep BC with eZ Platform 1.x while still allowing fallback to env vars

.travis.yml, app/AppKernel.php, app/config/config_behat.yml, behat.yml.dist, bin/.travis/trusty/setup_ezplatform.sh, bin/.travis/trusty/setup_from_external_repo.sh, composer.json
| Question | Answer |
| ------------ | ---------- |
| **Status** | Ready for a review |
| **JIRA issue** | [EZP-28375](https://jira.ez.no/browse/EZP-28375) |
| **Target version** | `2.0` |
| **BC break** | yes, for automated tests |
This PR improves running tests which require running eZ Platform installation (behat, REST functional) by moving most of setup logic to script which is a part of this meta-repository.
**TODO**
- ~Improve docker upgrade script.~ *removed after review*
=> EZP-28375: As a Maintainer I want CI to run tests on behat environment of eZ Platform v2

app/config/config.yml
> JIRA: https://jira.ez.no/browse/EZP-28637
This setting would mess forms in whole application which could generate some problems in frontend forms. AdminUI will set theme explicitly.
=> EZP-28637: Remove Bootstrap 3 references from application config

bin/.travis/trusty/setup_ezplatform.sh
This PR fixes `setup_ezplatform.sh` when used by dependencies to make composer install proper local checkout at the beginning. 
While my initial approach was faster it didn't take into account proper composer workflow (scripts, cache, etc.).
**TODO**
=> [Travis] Fixed setup_ezplatform.sh to make composer use local dependency

web/app.php
> Issue: https://jira.ez.no/browse/EZP-28714
> Replaces: #250
TL;DR; Anyone using Varnish for instance will need this, as they are supposed to disable symfony proxy and pass in trusted ip's for varnish (and tls proxy if there is one).
Review ping @wizhippo
=> EZP-28714: Allow trusted proxy env to be set when symfony proxy is off

app/AppKernel.php
dirname of /tmp would return /, native dirname(__DIR__) function return the parent of app which is good. But not in the SYMFONY_TMP_DIR case.
=> Fix SYMFONY_TMP_DIR when defined

.platform.app.yaml, .platform/services.yaml, app/config/env/platformsh.php
Enable Redis by default for Platform.sh usage.
* Turn Redis on, ever and always.  There's no compelling reason for someone to not use it on Platform.sh.
* Define a `rediscache` service and endpoint, which will get used for cache if available.
* Optionally define a `redissession` service and endpoint, commented out.  If a particular user desires to use a separate Redis instance they can by uncommenting a few lines.  If not, `rediscache` gets used for sessions as well.
* Remove the Memcache glue code, because we want people to use Redis instead.
* If for some reason Redis is broken, the system will still fall back to disk-based cache and sessions.  But really, try not to do that. :smile: 
This branch once accepted should be forward-ported to 2.x.
I spoke with a member of our support team, …
=> Use Redis-based sessions if Redis is available

app/config/ezplatform.yml
An easy one. Indetation is 4 spaces for all the file except for this part i'm changing now. Just in order to follow the same rule for everything.
ping @andrerom
=> Fix indentation for the default_ttl config var

composer.json
*This is my first PR to this project. I'm sorry if I did something wrong or not followed some required process.*
I propose to add `symfony/thanks` as a dependency of this project. [Symfony Thanks](https://symfony.com/blog/say-thanks-to-the-libraries-you-depend-on) allows users to say thanks to the libraries used in their projects. Despite its name, it's not a "Symfony thing", but a "PHP thing". It's already been included in Symfony, Laravel ([60de3a5](https://github.com/laravel/laravel/commit/60de3a5670c4a3bf5fb96433828b6aadd7df0e53)), Drupal (via Drupal Console [#3727](https://github.com/hechoendrupal/drupal-console/pull/3727)) and Akeneo PIM ([#7538](https://github.com/akeneo/pim-community-dev/pull/7538)).
Technically speaking, it's a tiny dependency that includes just a few lines of …
=> Added symfony/thanks dependency

bin/vhost.sh
Unfortunately, I forgot to change one line in #263 which breaks vhost.sh if BODY_SIZE_LIMIT environment variable is set
=> Bugfix : bin/vhost.sh broken by #263

app/config/env/platformsh.php
Fixing merge mistake in https://github.com/ezsystems/ezplatform/commit/5de7218173afc53e7e10d101ed48ba655413d4f0#commitcomment-27718059
=> Fixed bug: Wrong service loaded when enabling redis session on Platform.sh

app/config/routing.yml
And also for people often switching between versions.
I made it only handle root `/ez` as I'm unsure if anything in studio might be using sub routes of `/ez` still in it's current v1 form.
=> Redirect /ez route to /admin to help people upgrading 

app/config/security.yml
This brings back default path after login (for /admin/login url) removed in https://github.com/ezsystems/ezplatform-admin-ui/pull/373
https://github.com/ezsystems/ezplatform-ee/pull/75
=> EZP-26238: eZPlatform login screen redirecting to the link the user entered initially

doc/varnish/vcl/varnish3.vcl, doc/varnish/vcl/varnish4.vcl
> JIRA issue: [EZP-26491](https://jira.ez.no/browse/EZP-26491)
This PR adds the following line: https://github.com/ezsystems/ezplatform/blob/1.13/doc/varnish/vcl/varnish4_xkey.vcl#L31 to our other VCL templates. This is done to avoid ConflictingHeadersException, which is thrown by Symfony when there are both "X-Forwarded-For" and "Forwarded" headers set.
This is also suggested in the Symfony documentation: https://symfony.com/doc/2.8/http_cache/varnish.html#make-symfony-trust-the-reverse-proxy.
=> EZP-26491: Remove "Forwarded" header in the VCL to avoid ConflictingHeadersException

app/config/routing.yml
| **JIRA issue**     | [EZP-28962](https://jira.ez.no/browse/EZP-28962)
| **Requires** | ezsystems/ezpublish-kernel#2282
| **Target version** | `2.1`
| **Tests pass**     | TBD
| **Doc needed**     | no
This definition was missing from v1. It provides `OPTIONS` HTTP method support to REST API.
=> EZP-28962: The OPTIONS REST routes are not loaded anymore

app/config/env/platformsh.php
Due to this little typo, sessions could only be stored in dedicated redissession service up to this point
=> Fixed typo so session can be stored in rediscache in Platform.sh

composer.json
To enable several improvements in http cache in 0.5 and 0.6-rc1 and aim to send that to QA as part of 1.13.2 certification.
Todo:
=> [Composer] Bump http cache package version

composer.json
From time to time people try to install enterprise and it fails as composer tries to install via source. Latests today was one instance mentioned by @larseirik where someone tried to install 2.1@beta of ee hitting the "could not install from source github.com/..."
As composer by default picks source or dist automatically if user forgets to specify `--prefer-dist` this change will make sure composer prefers dist for eZ packages. See [Composer doc](https://getcomposer.org/doc/06-config.md#preferred-install).
This will *not* solve the same issue if user on purpose, knowingly or not, specifies `--prefer-source`. In that case I think composer will regardlessly pick what the command line user prefers. And as long as we don't have ldap setup to allow partners access to raw source this will not …
=> [Composer] Prefer dist for ez packages to avoid issues with updates.ez.no

doc/docker/Dockerfile-distribution
Environment variables were not taken into account due to pre-generated cache files.
Discovered while running SDC instances of 1.13 branch. Already fixed for 2.x branches (ref. #258)
Affected ezplatform and ezplatform ee
@vidarl and @andrerom for your acceptance
=> [Docker] Assuring empty cache in distribution image

doc/docker/Dockerfile-varnish
~~Status: varnish-modules 0.14 is not uploaded to download section, and besides from the looks of it there needs to be a new release of it to get it working on Varnish 6.0.~~
~ref: https://github.com/varnish/varnish-modules/issues/113~
Varnish modules 0.15 is out and supports Varnish 6.0, so we can herby bump version _(assuming test pass)_.
=> [Docker] Bump Varnish version to 6.0 for testing

app/config/ezplatform.yml
|      |     |
| --- | --- |
| **JIRA issue** | [EZP-29167](https://jira.ez.no/browse/EZP-29167) |
| **Related PR** | ezsystems/ezpublish-kernel#2346 |
| **Bug/Improvement**| no
| **New feature**    | yes
There is a demand for a generated URL aliases to be by default lowercase, which is more SEO-friendly behavior.
To keep BC for users that updated their installation, we've decided to change this default setting here, in the meta-repository.
This allows Kernel to behave in a BC way and achieve the goal for new installations.
Users updating their eZ Platform version will need to adjust that setting to their needs.
**TODO**:
=> EZP-29167: Set lowercase URL aliases as the default configuration

app/AppKernel.php, app/config/ezplatform.yml, app/config/ezplatform_behat.yml, composer.json
|      |     |
| --- | --- |
| **JIRA issue** | [EZP-28868](https://jira.ez.no/browse/EZP-28868)
| **Requires** | ~ezsystems/ezplatform-standard-design#2~<br>~ezsystems/ezplatform-standard-design#3~
| **Feature** | yes
| **Bug** | no
| **Doc needed** | yes
This PR enables Standard Design Bundle for eZ Platform `v2.2`.
The Bunde (see PR ezsystems/ezplatform-standard-design#2):
```yaml
ez_platform_standard_design:
override_kernel_templates: false
```
- No-layout view (`viewbase_layout.html.twig`).
- Page Layout (`pagelayout.html.twig`).
- Full Content view (`default/content/full.html.twig`).
- Inline Content view (`default/content/line.html.twig`).
- Linked text Content view (`default/content/text_linked.html.twig`).
- Embed Content view (`default/content/embed.html.twig`).
- Embed Image …
=> EZP-28868: Enabled eZ Platform Standard Design Bundle

.platform.app.yaml, .platform/services.yaml
The MySQL column sizes limited installation to Platform.sh infrastructure with the previous setting of the database (MariaDB 10.1). This PR upgrades the MariaDB version to 10.2. Unrelated to this - It also bumps PHP to 7.2 by default (was 7.1) for improved performance and features.
NOTE: These changes should also be applied to the following repositories:
- https://github.com/ezsystems/ezplatform-ee
- https://github.com/ezsystems/ezplatform-ee-demo
- https://github.com/ezsystems/ezplatform-demo
=> EZP-29324: Upgrade to MariaDB 10.2 (+PHP 7.2) for eZ Platform Cloud

composer.json
Some time ago @damianz5 introduced to our Enterprise Edition demo a composer command which was the wrapper for `ezplatform:install <type>` command. We've tested that there and it's been proven to be a great simplification.
This PR introduces the same command wrapper:
```bash
composer ezplatform-install
```
but using `clean` type for open source version of eZ Platform. The idea is to adjust it when merging from this upstream to other meta-repositories by setting a proper install `<type>`.
Justification for that is the fact that every meta-repository (`ezplatform`, `ezplatform-demo`, `ezplatform-ee`, `ezplatform-ee-demo`) uses its own installer type and there is no point to use a different one (e.g. demo sites will crash when clean one is used).
=> [Composer] Simplified the command to install eZ Platform

bin/vhost.sh, doc/apache2/Readme.md, doc/apache2/vhost.2.2.template, doc/apache2/vhost.template
Needed to unblock https://github.com/ezsystems/developer-documentation/pull/269
Optional followup:
- Add/use Apache docker image to see if we can have some of the test runs using apache instead of Nginx
=> [Doc] Update Apache vhost examples to have one fully working for 2.4

app/config/env/generic.php, doc/docker/redis-session.yml
This one fixes [EZP-29388](https://jira.ez.no/browse/EZP-29388)
In symfony 3, default session_handler is set to [handler_id:  session.handler.native_file](https://github.com/symfony/symfony-standard/pull/904).
That means that it is not possible to override session handler in php.ini without changing config back to `handler_id:  ~`
Therefore, in this PR we inject session handler using environment variable
If accepted, this PR replaces https://github.com/ezsystems/ezplatform/pull/284
=> EZP-29388: Not possible to set session handler via docker

app/config/config.yml, app/config/default_parameters.yml, app/config/env/generic.php
Currently the session save_path is set to use the filesystem by default. When trying to use redis the session save_path string would need to be modified. There is check for a env var in generic.php that sets the session.save_path variable however it isn't being used in the config.yml and continues to save to the filesystem instead of redis.
=> Fix session save_path

app/config/config.yml, app/config/default_parameters.yml, app/config/env/generic.php, app/config/env/platformsh.php, app/config/parameters.yml.dist
Some further cleanup on session env variables, and move some non handler based params to use `env()` and hence fix inline todo.
Besides cleanup, this fixes that platformsh.php was setting wrong session.save_path parameter.
This is followup to #307 (done in 2.2-dev) and #304
It also tries to clarify a bit the confusion in #306
review ping @alongosz, @raupie, @Plopix
=> Fix usage of session env variables and move some over to use env()

.env, .travis.yml, doc/docker/install.yml
JIRA: https://jira.ez.no/browse/EZP-29455
Added:
- notifications for Slack on broken builds.
- running PlatformUI tests on Varnish
Currently the build for 1.7 is failing because of Composer exceeding memory limits - I've increased it to 2GB (tested that 1GB is too low).
=> EZP-29455: Prepare regression setup with default configuration

app/console, web/app.php
> Fixes https://jira.ez.no/browse/EZP-29034
Since friendsofsymfony/http-cache version 1.4.5, eZ Platform 1.7 branch can't be installed or used unless one uses --no-warmup on cache clear commands, or clears caches with rm -rf. Class cache generated by the console conflicts with that from web.
This fixes it by:
- Cherry-picking https://github.com/ezsystems/ezplatform/commit/5fdf60c698760eda387286d5885ffe67ee32191f which ensures class cache is not used on PHP7, as it has no performance benefit there (Also: Disable bootstrap.php.cache on PHP 7 so we are in sync with how Symfony does it)
- Ensure that when cache is cleared by console command in PHP5, --no-warmup is enforced. https://github.com/ezsystems/ezplatform/commit/7e6b4716480d16e45d0ac4bd75b2b319cff42ff7 This is a filthy hack 💩 …
=> EZP-29034: Cannot install ezplatform on 1.7 branch

app/config/config.yml, app/config/dfs/dfs.yml
Default to utf8mb4 charset in eZ Platform, since we're defaulting to utf8mb4 in 2.2+ kernel schema.
(merge in 2.2 & master)
=> Default to utf8mb4 charset

.env, .platform.app.yaml, doc/docker/Dockerfile-app, doc/docker/Dockerfile-nginx, doc/docker/base-prod.yml, doc/docker/distribution.yml
PHP 7.2 should be rather stable now both on our side _(ezpublish-legacy just got patches as well)_, p.sh side and php side. So time to take advantage of the 5-7% speedup :)
As a minor bonus 7.2 image is also [38mb smaller](https://hub.docker.com/r/ezsystems/php/tags/) as it builds on Debian 9 _(:stretch-slim)_ instead of 8 _(:jessie)_.
This also adapts Dockerfiles to not hard code php image we use, in order to cleanup here and also get rid of things like https://github.com/ezsystems/docker-php/blob/master/bin/.travis/test.sh#L80-L86.
=> [Docker + p.sh] Switch to PHP 7.2 & change Dockerfiles to take version by ARG

bin/.travis/trusty/setup_ezplatform.sh
This is a followup to https://github.com/ezsystems/ezplatform/pull/319#issuecomment-414930052
I've tested the solution here: https://github.com/ezsystems/ezplatform-admin-ui/pull/604
First commit (without any changes in this PR) failed as expected.
Second commit (with changes from this PR) also failed (that was not expected).
After I've cleared the cache on Travis for AdminUI it passed.
So, it looks like in order to fix Travis we should merge this and then clear cache for all affected repositories (not a problem).
=> [Travis] Perform full checkout to fix Travis setup

app/config/cache_pool/cache.memcached.yml, app/config/cache_pool/cache.redis.yml, app/config/default_parameters.yml
Overrides the default cache namespace: https://github.com/symfony/symfony/blob/3.4/src/Symfony/Bundle/FrameworkBundle/DependencyInjection/Compiler/CachePoolPass.php#L33-L38
This makes sure cache is shared across a cluster no matter what the path of install is used or what Symfony Env you are using, hence making sure changes done on a dev env is affecting prod as well _(if those use different db's then inline doc here implies separate namespace should be used, or user should opt for default behavior instead)_
Open questions:
- Should this be master only maybe, as it affects cache logic for deployments and thus might be a bit intrusive to ship in a patch release
Todo:
- Doc, once approach is approved
-------
@emodric You'll see two first commits here with different approaches. In the end …
=> [YML] Add default cache prefix in order to share cache across cluster 

.travis.yml, bin/.travis/runcommand.sh, doc/docker/base-dev.yml, doc/docker/base-prod.yml
This is a followup to comment in https://github.com/ezsystems/ezplatform-demo/pull/92/files/b83035746dbf73caaa8d34edbab798814711ee15#diff-12e91abffee0d4e830c705c6d7258aa7R94
When developing tests across different repositories we're sometimes adding temporary Composer dependencies ([example of how it's done](https://gist.github.com/mnocon/c61372eba4f369f3e45cb9e962444fe5)). This operation performs composer operations directly on the `app` container, which does not use `COMPOSER_MEMORY_LIMIT` (it's only set for `install_app` - https://github.com/ezsystems/ezplatform/commit/add8d279f1d7b3b2666bb72935ff23c795bf812c#diff-12da65584b74987bec78f37c6b423dbfL23). For me it makes sense to set the value in `app` too.
Sometimes the tests are failing, because there are concurrency issues when clearing …
=> [Travis] Improve PlatformUI stability, set COMPOSER_MEMORY_LIMIT

behat.yml.dist, composer.json
JIRA: https://jira.ez.no/browse/EZP-29570
This PR adds Behat screenshots for Travis.
It's extremely useful to see a screenshot taken in the moment when a Behat Selenium test failed - this speed immensely test debugging. The solution should ideally be:
- available both for public and enterprise bundles
- free
- available in PRs from forks for community PRs
By default, Travis only allows uploading artifacts to Amazon S3, which I don't think suits us (while cheap it's not free after a year and I'd be a little bit worried of leaking the credentials in the public).
There are Behat extensions that allow for using other image hosting services, such as:
- https://github.com/Lakion/MinkDebugExtension
- https://packagist.org/packages/bex/behat-screenshot
The first one works only with Imgur, which …
=> EZP-29570: Add screenshots for Behat on Travis

app/config/config.yml
https://jira.ez.no/browse/EZP-29675
=> EZP-29675: Correct JMS translations config to exclude node_modules folder from searching translations

.platform.app.yaml, .platform/services.yaml
Small bug in the solr template for Platform.sh
We need to point the `relationship` to the `endpoint` defined in [services.yml](https://github.com/ezsystems/ezplatform/blob/1.13/.platform/services.yaml#L50)
=> Fixed bug in solr template for Platform.sh

app/config/env/platformsh.php
This fixes a bug for ezplatform platform.sh customers with enterprise subscriptions. Platform.sh creates solr_cores named after the environment and not from the platform.sh services.yml file. You need to set the solr_core variable dynamically from the solr relationship using the path entry.
=> Set solr_core variable from platform.sh relationships

doc/apache2/Readme.md, doc/apache2/vhost.template, doc/nginx/Readme.md, doc/nginx/vhost.template
> Implement https://jira.ez.no/browse/EZP-29830
> Ready for review
In the wake of [EZSA-2018-009](http://share.ez.no/community-project/security-advisories/ezsa-2018-009-do-not-interpret-php-phar-uploads) we should change the web server readmes and vhost templates accordingly.
This will return `HTTP 403 Forbidden` for such files, which is easy to track in dedicated log files, if wanted.
=> EZP-29830: Disable executables in the var directory

doc/docker/Dockerfile-distribution, doc/docker/README.md
This PR makes it possible to change COMPOSE_PROJECT_NAME without altering doc/docker/Dockerfile-distribution.
Instead you may use docker build argument as documented  in README
=> Added build argument DISTRIBUTION_IMAGE to Dockerfile-distribution

composer.json
> https://jira.ez.no/browse/EZP-29852
Use [sensiolabs/security-checker](https://github.com/sensiolabs/security-checker/tree/v5.0.1) instead of [roave/security-advisories](https://github.com/Roave/SecurityAdvisories). security-advisories blocks installation in certain cases, leading people to remove it, thus losing protection in the cases where they could benefit from it. security-checker is less intrusive, showing a warning instead of blocking the install.
See Travis test output ("No packages have known vulnerabilities.") for how it looks.
=> EZP-29852: Use security-checker instead of security-advisories

.env
https://jira.ez.no/browse/EZP-29985
Updating Chrome version on Travis.
Before: 60.0.3112.113 (released August 24, 2017)
After: 71.0.3578.98 (released December 12, 2018)
This PR is marked as WIP until I sort out all the issues related to the upgrade (in https://github.com/ezsystems/ezplatform-page-builder/pull/289).
=> EZP-29985: Update Selenium container on Travis

composer.json
Twig 2.6.1 constains a breaking change/bug that breaks AdminUI - it's impossible to browse Content, Form and Page tabs in the Admin panel.
More about the issue: https://github.com/twigphp/Twig/issues/2810
Example failure:  https://res.cloudinary.com/ezplatformtravis/image/upload/v1547459400/screenshots/vendor_ezsystems_ezplatform-form-builder_features_formbuildertests_feature_11_c8a6wf.png
(taken from https://travis-ci.com/ezsystems/ezplatform-form-builder/jobs/170142669 )
=> [Composer] Add conflict for Twig 2.6.1

doc/docker/selenium.yml
Recently (in https://github.com/ezsystems/ezplatform/pull/352) the shared memory has been bumped to 512mb. There are fewer failures, but they still sometimes happen, for example:
https://travis-ci.com/ezsystems/ezplatform-form-builder/builds/98801861?utm_source=slack&utm_medium=notification
I believe increasing it to 1gb will make the tests stable, as right now the failures happen rarely.
(I've used format from https://docs.docker.com/compose/compose-file/#shm_size )
=> Increase shared memory to 1gb

composer.json
Currently it's not possible to install 2.2 EE branch, example: https://travis-ci.com/ezsystems/ezplatform-page-builder/builds/99270204
```
Your requirements could not be resolved to an installable set of packages.
Problem 1
- ezsystems/ezplatform-page-fieldtype v1.0.1 requires ezsystems/ezplatform-http-cache ^0.7 -> satisfiable by ezsystems/ezplatform-http-cache[0.7.x-dev].
- ezsystems/ezplatform-page-fieldtype v1.0.2 requires ezsystems/ezplatform-http-cache ^0.7 -> satisfiable by ezsystems/ezplatform-http-cache[0.7.x-dev].
- ezsystems/ezplatform-page-fieldtype v1.0.3 requires ezsystems/ezplatform-http-cache ^0.7 -> satisfiable by ezsystems/ezplatform-http-cache[0.7.x-dev].
- ezsystems/ezplatform-page-fieldtype v1.0.4 requires ezsystems/ezplatform-http-cache ^0.7 -> satisfiable by …
```
=> [Composer] Use http-cache 0.7.x in 2.x version

behat.yml.dist
https://github.com/ezsystems/behat-screenshot-image-driver-cloudinary/pull/2 is merged, so it should be possible now to limit the number of screenshots taken in a single test run.
We're using free plan of Cloudinary, which limits us to 20 000 screenshots in 30 days. That is a lot and is enough for our normal use, but the problem is in Pull Requests with dependencies: Travis tests are failing in them and a lot of screenshots is taken. 
Limiting the number of screenshots taken in a single job to 10 should limit the number when the PR is in WIP stage or has a dependency, but it should keep being useful when a PR really has issues.
=> Limit number of screenshots to 10 for a single job

composer.json
Options added in https://github.com/ezsystems/ezplatform/pull/358 require `ezsystems/behat-screenshot-image-driver-cloudinary` in version 1.1.0 - it's downloaded in 2.3 branch, but not in this one.
Changed Composer requirement to allow for non-breaking updates.
=> [Composer] Increase Behat Cloudinary Screenshot version

doc/varnish/varnish.md, doc/varnish/vcl/varnish4_xkey.vcl
Story: https://jira.ez.no/browse/EZP-30170
Additional awareness / review ping:
- @vidarl  _Demo Cloud / Platform.sh impact?_
- @Plopix  _eZ Launchpad impact?_
Todo:
=> EZP-30170: [2.5LTS] Drop Varnish 4 + get rid of duplicated VCL in meta repo

.platform.app.yaml
Required changes for the upcoming eZ Platform v2.5 in order to have Webpack Encore running on eZ Platform Cloud.
jira: https://jira.ez.no/browse/EZP-30183
=> EZP-30183: Support webpack for eZ Platform Cloud

composer.json
Until bug in webpack-encore-bundle is fixed we need avoid installing version 1.2 (https://github.com/symfony/webpack-encore-bundle/pull/51 or https://github.com/symfony/webpack-encore-bundle/pull/50)
=> Added conflict to webpack-encore-bundle 1.2.0 and 1.2.1

composer.json
This PR removes automatic execution of `bin/console ezplatform:graphql:generate-schema` after `composer install`.
When there's no database schema (or even database itself in some cased) installed yet (done by `ezplatform:install`) the `composer install` crashes. This is quite common case for people installing for the first time.
I'm aware that it's not possible to use GraphQL without generating this schema, but we need to find alternative solution and right now just document that it's required manual step (maybe installation guide? cc @DominikaK).
=> [Composer] Removed generating GraphQL schema after composer install

app/AppKernel.php, app/config/config.yml, app/config/default_parameters.yml, app/config/parameters.yml.dist, composer.json
| **JIRA issue**     | [EZP-29938](https://jira.ez.no/browse/EZP-29938)
| **Requires** | <ul><li>ezsystems/ezpublish-kernel#2552</li><li>ezsystems/doctrine-dbal-schema#1</li></ul>
| **Bug/Improvement**| no
| **New feature**    | yes
| **Target version** | `eZ Platform 2.5 LTS`
| **Tests pass**     | [yes](https://travis-ci.org/ezsystems/ezplatform/builds/502501048)
| **Doc needed**     | yes
This PR:
- adds `new EzSystems\DoctrineSchemaBundle\DoctrineSchemaBundle()` to the list of bundles in `app/AppKernel.php`,
- parametrizes `doctrine.dbal.connections.default.charset` and adds a possibility to provide it in `app/config/parameters.yml` as  `env(DATABASE_CHARSET)` parameter.
To install eZ …
=> EZP-29938: Enabled PostgreSQL support via DoctrineSchemaBuilder

.platform/services.yaml
The syntax we use for solr config on platform.sh has been revoked by Platform, ref. https://github.com/platformsh/platformsh-docs/commit/f7f79d74223856f4d03a2b71954f1e865aef28ce#diff-3c2bd0d7625d58625747452f091e39af
So introducing the old "!archive" syntax. Without it, you'll simply won't be able to deploy with solr on Platform.sh
=> [Platform.sh] Changed to 'old' solr config syntax

.platform.app.yaml
This PR makes it handy to let composer use a github token when communicating with github. A github token is needed if you are using private repos on github, or need to avoid githubs rate limit.
=> [Platform.sh]Added support for injecting github token via environment variable

composer.json
Q: Which is the better approach? "~3.2.0@dev" or "^3.1.0@dev"?
Discovered while testing https://github.com/ezsystems/ezplatform-admin-ui/pull/886.
=> Update ezplatform-admin-ui-assets version for 2.4 in composer.json

.travis.yml, app/config/ezplatform.yml
| **JIRA issue** | [EZP-30318](https://jira.ez.no/browse/EZP-30318)
| **Resolves**     | <ul><li>[EZP-30305](https://jira.ez.no/browse/EZP-30305) (#373)</li><li>[EZP-29291](https://jira.ez.no/browse/EZP-29291)</li></ul>
| **Target version** | `2.5 (master)`
| **Tests pass**     | yes
| **Doc needed**     | update for places where `admin_group` is referenced
v2 at some point ended up with lots of duplicate config due to the new admin siteaccess and it's group, however we can rather set `default` here to avoid that.
For demo this will mean we can simplify [from](https://github.com/ezsystems/ezplatform-demo/blob/master/app/config/ezplatform.yml#L42-L93) => to:
```yml …
```
=> EZP-30318: [DX] Simplified ezplatform.yml to avoid duplicated config

composer.json
| Question      | Answer
| ------------- | ---
| Tickets       | [EZP-30302](EZP-30302)
| Bug fix?      | yes
| New feature?  |no
| BC breaks?    |no
| Tests pass?   | yes
| Doc needed?   |no
| License       | [GPL-2.0](https://github.com/ezsystems/ezplatform-admin-ui/blob/master/LICENSE)
=> EZP-30302: Webpack encore generates assets in wrong directory on Windows

ez.webpack.config.manager.js
I'm using a symlink for `ezplatform-admin-ui` on my local. So `<EZ_ROOT>/vendor/ezsystems/ezplatform-admin-ui` links to `~/Projects/ez/bundles/ezplatform-admin-ui`.
Also I have local `ExtendedAdminUIBundle` bundle, and wanted to replace some items using `ez.config.manager.js`.
`src/ExtendedAdminUIBundle/Resources/encore/ez.config.manager.js`:
```
const path = require('path');
module.exports = (eZConfig, eZConfigManager) => {
eZConfigManager.replace({
eZConfig,
entryName: 'ezplatform-admin-ui-alloyeditor-js',
itemToReplace: path.resolve(__dirname, '../../../../vendor/ezsystems/ezplatform-admin-ui/src/bundle/Resources/public/js/scripts/fieldType/base/base-rich-text.js'),
newItem: path.resolve(__dirname, '../public/js/base-rich-text.js'),
});
};
```
Without this fix I was unable to run `yarn …
=> Handle symlinks for itemToReplace in eZConfigManager.replace

bin/compile_assets.sh, composer.json
> JIRA: https://jira.ez.no/browse/EZP-30412
Previously it was always using `dev` assets which was inconvenient for people who were using composer on production environments. This PR changes default behavior to use production ready assets unless `SYMFONY_ENV=dev`.
=> EZP-30412: Composer is always using dev for generating encore assets

doc/docker/Dockerfile-distribution
[These instructions](https://github.com/ezsystems/ezplatform/blame/8e09876e93b79c6bb09b95e459f09a0f8de75964/doc/docker/README.md#L221-L248) do not work on 2.5.0 because yarn is missing when building distribution image.
This PR adds a build stage where yarn is available
=> [Docker]Fixed building of distribution image (for v2.5.0)

.travis.yml, bin/.travis/trusty/update_docker.sh
Updates to use Ubuntu xenial (16.04) which seems to be a bit faster and prefered from Travis side.
Change docker script to only update docker if needed as it won't be needed here (so saving time on that)_, however repos still using trusty will need it still.
Thus this opens the door for sub repos to migrate to use xenial as well, and saving docker update when doing so.
_Script tested on trusty as well to make sure it install docker updates when needed._
=> [Travis] Upgrade to use xenial, & skip docker upgrade if not needed

.travis.yml, bin/.travis/run_rest_tests.sh
This is a follow-up for changes from [EZP-28032](https://jira.ez.no/browse/EZP-28032) merged via #399.
Seems we still have some leftover Kernel REST tests that were executed instead of those from the new package.
The PR changes the way we execute REST functional tests to run them directly from [`ezplatform-rest`](https://github.com/ezsystems/ezplatform-rest) package prior installing its dev dependencies.
The reason we should do it is simple - those tests were written for the vendor packages (like PHPUnit) defined by the package `composer.json` - not the one from the meta-repository.
This PR also drops REST behat tests as they're all covered by the functional tests of [eZ Platform REST Bundle](https://github.com/ezsystems/ezplatform-rest).
**TODO**:
=> [Travis] Set REST Bundle tests to run directly from its package

app/config/default_parameters.yml
No big deal here. When adding something to my default_parameters.yml in my project, looks the cs inspector in the IDE and so, this blank space is deleted. I noticed this when reviewing the PR i was working on. 
But still, if we have it deleted here, it won't popup in the future to more people. 
Let me know if you want a ticket for this. 
ping @lserwatka @andrerom @adamwojs
=> delete unneded blank space at the end of line

.env
All Travis build are currently failing, unable to login:
Example:
https://travis-ci.org/ezsystems/ezplatform/builds/542009341
This is caused by yesterday's release of Selenium Docker image, which upgraded Chrome version (see: https://github.com/SeleniumHQ/docker-selenium/issues/922 )
The workaround proposed in https://github.com/minkphp/MinkSelenium2Driver/issues/293#issuecomment-499458269 does not work for us, so the only option for me is keep using the latest working version until we figure this out.
=> Use old Docker-Selenium container

.env
Increasing COMPOSER_MEMORY_LIMIT to fix issues with Composer on Travis. Examples:
https://travis-ci.org/ezsystems/repository-forms/jobs/544973712#L465
https://travis-ci.org/ezsystems/ezplatform-admin-ui/jobs/544726667
I've tried increasing the minimum supported version of our packages, but the result is not really worth it:
```
[457.1MiB/144.71s] Memory usage: 457.09MiB (peak: 2143.09MiB), time: 144.71s - before
[457.1MiB/152.79s] Memory usage: 457.07MiB (peak: 2122.2MiB), time: 152.79s - after
```
Value is set to the same as in PageBuilder.
=> [Travis] Increase Composer memory limit to 4g

app/config/config_behat.yml
JIRA: https://jira.ez.no/browse/EZP-30642
Added a dedicated Travis log from which we will display errors on Travis (added in https://github.com/ezsystems/ezplatform-admin-ui/pull/1012/files)
=> EZP-30642: Added Travis dedicated error log

config/packages/ezplatform.yaml, config/packages/framework.yaml
> JIRA: https://jira.ez.no/browse/EZP-30656
I intentionally moved ESI configuration to `ezplatform.yaml` to indicate that it's used by eZ Platform.
=> EZP-30656: render_esi is not configured by default

app/config/env/platformsh.php
We don't set swiftmailer config correct on Platform.sh
**IMPORTANT**
When merging this to 2.4 and later, the following change is needed:
```patch
-if ($container->getParameter('mailer_host') === '127.0.0.1') {
+if ($container->resolveEnvPlaceholders($container->getParameter('mailer_host'), true) === '127.0.0.1') {
```
=> EZP-30723:Mailing does not work on Platform.sh

composer.json
Removing minimum-stability and prefer-stable section from this composer.json , as currently beta versions of our packages are installed when doing composer install on master. 
Proof: https://travis-ci.org/ezsystems/ezplatform/jobs/553990882
=> [Composer] Removed min-stability and prefer-stable sections

.env, config/packages/doctrine.yaml
> JIRA: https://jira.ez.no/browse/EZP-30667
This is a followup fixing issue mentioned in https://github.com/ezsystems/ezplatform/pull/428#pullrequestreview-257949806
It changes `DATABASE_DRIVER` env meaning - it will now define driver used by doctrine to connect to the database i.e. `pdo_mysql`. `DATABASE_PLATFORM` now handles prefix used to distinguish to which DB platform you are connecting to i.e. `mysql`, `pgsql`.
=> EZP-30667: Made database charset and collation configurable via dotenv

config/packages/ezplatform.yaml, config/packages/framework.yaml
> JIRA: https://jira.ez.no/browse/EZP-30804
It removes `handler_id` setting from `framework.yaml` so that configuration from `ezplatform.yaml` is not overrode. Also I made a mistake and used envs to configure this setting but this is not possible in this place. This wasn't visible because of `framework.yaml` taking precedence.
I left `SESSION_HANDLER_ID` and `SESSION_SAVE_PATH` in `.env` intentionally as it will be used by Platform.sh once we bring back support for it in 3.0.
=> EZP-30804: Removed env use from session handler configuration

config/packages/behat/framework.yaml
Enabling https://symfony.com/doc/current/reference/configuration/framework.html#test so that Symfony2Extension is able to get private services from the container.
What happens right now:
Hooks Context has the logger service injected - https://github.com/ezsystems/BehatBundle/blob/master/src/lib/Browser/Context/Hooks.php#L30
This is causing the tests to fail with error:
```
[Symfony\Component\DependencyInjection\Exception\ServiceNotFoundException]                                                                                                                               
The "logger" service or alias has been removed or inlined when the container was compiled. You should either make it public, or stop using the container directly and use dependency injection instead.  
```
Source: …
=> [Behat] Marked Behat env as test

app/config/ezplatform_behat.yml
JIRA: https://jira.ez.no/browse/EZP-30801
I've investigated that error and I didn't find anything wrong with maplocation field type, but verified that in Chrome with throttling enabled the time between clicking "Publish" and displaying the notification can be quite long. 
We're already waiting for the notification to appear for 20 seconds (https://github.com/ezsystems/ezplatform-admin-ui/blob/master/src/lib/Behat/PageElement/Notification.php#L36), it makes sense to me to display it for the same amount.
Note to self: this required careful merging upstream, as the config is in other place in 3.0.
=> [Behat] Increased success notification timeout in Behat env

app/config/security.yml
Enables CSRF token in login forms by default. This is a publicly known security issue which isn't merged yet due to a problem with kernel tests, see separate PR for that. Users have been recommended to enable it.
https://share.ez.no/community-project/security-advisories/ezsa-2019-004-csrf-token-in-login-form-is-disabled-by-default
⚠ The kernel SessionTest will fail here, but passes if https://github.com/ezsystems/ezpublish-kernel/pull/2693 is merged.
=> Enable CSRF token in login form by default

.env
Some Travis builds are failing because of Composer memory issues, see:
https://travis-ci.com/ezsystems/ezplatform-page-fieldtype/jobs/226435569
```
install_dependencies_1  | Loading composer repositories with package information
Updating dependencies (including require-dev)
install_dependencies_1  | PHP Fatal error:  Allowed memory size of 2147483648 bytes exhausted (tried to allocate 4096 bytes) in phar:///usr/local/bin/composer/src/Composer/DependencyResolver/Solver.php on line 223
install_dependencies_1  | Fatal error: Allowed memory size of 2147483648 bytes exhausted (tried to allocate 4096 bytes) in phar:///usr/local/bin/composer/src/Composer/DependencyResolver/Solver.php on line 223
install_dependencies_1  | Check https://getcomposer.org/doc/articles/troubleshooting.md#memory-limit-e …
```
=> [Travis] Increased default Composer memory limit

composer.json
Increasing version of BehatBundle to 7.0, which has been introduced because of https://github.com/ezsystems/BehatBundle/pull/92#pullrequestreview-277660297
The code in this version is 100% compatible with BehatBundle 6.5.4, but it drops support for older kernel versions. 
People using eZ Platform 2.5 should be able to update to BehatBundle 7.0 without any issues.
BehatBundle 6.5 - can be used with all versions until eZ Platform 3.0 is released
BehatBundle 7.0 - can used with eZ Platform ^2.5, contains new features, but keeps old code
BehatBundle 8.0 (current master) - can used with eZ Platform ^3.0, new features, does not contain old code
Note to self: this has to be changed to ^8.0.0@dev when merging upstream
=> [Composer] Increased BehatBundle version

config/packages/ezplatform_assets.yaml, config/packages/webpack_encore.yaml
| **JIRA issue**     | [EZP-30714](https://jira.ez.no/browse/EZP-30714)
| **Target version** | `master (3.0@dev)`
| **Tests pass**     | yes
| **Doc needed**     | no
Currently adding project-level Encore configuration (as a default build) results in HTTP 500 error when trying to use `encore_entry_*_tags` Twig functions.
This PR:
=> EZP-30714: Fixed default Webpack Encore configuration

web/app.php
Target: 1.7, 1.13, 2.5, master. It has passed QA.
Prevent direct use of app.php in URLs, needed for pSH. It's not possible to do this in `.platform.app.yaml` according to pSH support, so we do it in app.php itself.
The regexp blocks `/folder/app.php` and `/app.php` (for uri-based siteaccess), but allows `/folder/folder/app.php` (two or more levels). It also blocks `/app.php/foo` and `/app.php?foo` and `/app.php#foo`, but allows `/app.php-foo`, `/app.php.foo`, etc.
=> EZP-30716: Prevent accepting app.php in URL in Platform.sh

config/packages/ezplatform.yaml
| **JIRA issue**     | [EZP-30906](https://jira.ez.no/browse/EZP-30906)
| **Target version** | `master (8.0@dev)` for eZ Platform `v3.0`
| **BC breaks**      | yes
| **Tests pass**     | [yes](https://travis-ci.org/ezsystems/ezplatform/builds/581547772)
| **Doc needed**     | yes
>List of all related PRs:
https://github.com/ezsystems/ezplatform-design-engine/pull/23
https://github.com/ezsystems/ezplatform-http-cache/pull/100
https://github.com/ezsystems/ezplatform-richtext/pull/66
https://github.com/ezsystems/ezplatform-user/pull/47
https://github.com/ezsystems/ezpublish-kernel/pull/2759
https://github.com/ezsystems/repository-forms/pull/314
>EE: …
=> EZP-30906: Removed deprecated templating component integration

bin/.travis/trusty/setup_ezplatform.sh
After https://github.com/ezsystems/ezplatform-admin-ui-modules/pull/200 GraphQl is always used in the product and the schema must be generated before AdminUI can be used.
=> Added graphql schema generation after database install

.travis.yml
JIRA: https://jira.ez.no/browse/EZP-30884
See https://github.com/ezsystems/ezplatform/pull/451/commits/4d61312882124bb39d6aa8c1c1e2cea1feb6790e for real changes
Adding a new job, running only in nightly builds and triggred ones.
=> EZP-30884: Added Travis setup

.platform.app.yaml, .platform/services.yaml, app/config/config.yml, app/config/default_parameters.yml, app/config/parameters.yml.dist, bin/platformsh/pre_start-per_node-clear_cache.sh, doc/platformsh/INSTALL.md, doc/platformsh/README.md
Goals, most trying to improve DX:
- Define clear hints on what should be done on Platform.sh Enterprise Dedicated Cluster, for partner and for Platform.sh staff as well
- Update config to cover more common needs inline
- _e.g. redis cache clear (NB: varnish/fastly to be covered later as followup)_
- Simplify:  use COMPOSER_AUTH  and ~change to composer flavour~ _(Skipped for now as we need to install another version of node.js in build step)_
- Simplify: Align Enterprise and Open Source doc to cover all in Open source doc to avoid EE doc getting out of sync, possible now thanks to change to suggest generic COMPOSER_AUTH use for any auth needs
Target 2.5LTS and up for simplicity, we could consider bringing this to 1.13LTS as well if we anticipate further changes there (and hence conflicts …
=> [Platform.sh] Revise bundled config & inline doc

config/bundles.php, config/packages/behat/ezplatform.yaml, config/packages/dfs/dfs.yml, config/packages/ezplatform.yaml, config/packages/ezplatform_admin_ui.yaml, config/packages/security.yaml
| **JIRA issue**     | [EZP-30636](https://jira.ez.no/browse/EZP-30636)
| **Bug/Improvement**| no
| **New feature**    | yes
| **Target version** | eZ Platform `v3.0`
| **BC breaks**      | yes
| **Tests pass**     | TBD
| **Doc needed**     | yes
This PR enables eZ Platform Core Bundle and uses `ezplatform` extension instead of `ezpublish`.
**TODO**:
=> EZP-30636: Enabled eZ Platform Bundle

.platform.app.yaml, bin/platformsh/pre_start-per_node-clear_cache.sh
Fixes:
`W: /bin/dash: 16: ./bin/platformsh/pre_start-per_node-clear_cache.sh: Permission denied`
Fixes a few issues:
- Missing execution flag
- Make sure deploy won't fail if execution flag is missing
- _Issue with updates.ez.no packages due to [ongoing Satis/Composer issue](https://github.com/composer/composer/pull/8331)_
- Swap script to only need shell instead of bash
=> [Platform.sh] Change to fix execution bit issues with cache script

.env, doc/docker/install-dependencies.yml, doc/docker/install_script.sh
According to this [doc](https://symfony.com/doc/current/configuration.html#configuration-based-on-environment-variables) : `The existing env vars are never overwritten by the values defined in .env, so you can combine both.` That seems to be only partially true..
So in .env we have :
```
DATABASE_URL=${DATABASE_PLATFORM}://${DATABASE_USER}:${DATABASE_PASSWORD}@${DATABASE_HOST}:${DATABASE_PORT}/${DATABASE_NAME}
```
Variables like `DATABASE_NAME` and `DATABASE_PORT` are also set in the `.env` file..
However, it does not work to then change `DATABASE_NAME` via environment variable. It must be changed in `.env` too, because `DATABASE_URL` is defined there. Or, as I do here, redefine `DATABASE_URL` instead
~note : https://github.com/ezsystems/ezplatform/pull/464 should be merged first, and …
=> Docker on 3.x

doc/docker/base-dev.yml, doc/docker/base-prod.yml
Required by https://github.com/ezsystems/ezplatform-page-builder/pull/406 to fix repository-forms on EE demo tests, which are failing because of memory issues.
=> [Docker] Allowed to set PHP memory limit through env

composer.json
| **JIRA issue**     | [EZP-31132](https://jira.ez.no/browse/EZP-31132)
| **Target version** | `2.5.x` and up.
| **Tests pass**     | TBD
| **Doc needed**     | no
This requirement is needed to avoid installing monolog 2, which indirectly requires Symfony 5 (via `symfony/monolog-bundle`).
The issue was reported as symfony/monolog-bundle#330, however we needed to unblock right now CI failing all over the place.
**TODO**:
=> EZP-31132: [Composer] Explicitly required monolog/monolog:^1.25.2

config/services.yaml
| **JIRA issue**     | [EZP-30769](https://jira.ez.no/browse/EZP-30769)
| **Bug**| yes
| **New feature**    |no
| **Target version** | `master`
| **BC breaks**      |no
| **Tests pass**     | yes
| **Doc needed**     |no
This PR registers translation commands which are not registered by jms/translation-bundle. This is because we are using behat/bahet in version 3.5.0 which still requires Symfony ClassLoader. It results in that commands are not registered in `JMS/TranslationBundle/DependencyInjection/JMSTranslationExtension.php:36`
```
if (!class_exists('Symfony\Component\ClassLoader\ClassLoader')) {
$loader->load('console.xml');
}
```
**TODO**:
=> EZP-30769: Registered missing translations commands

composer.json
JIRA: https://jira.ez.no/browse/EZP-31189
Trying to unblock failing (https://travis-ci.org/ezsystems/ezplatform/builds/617477582) Travis tests by limiting memory required by Composer.
Merging: If this is approved I will prepare a PR to 1.13 with suggested changes and send it to review - if approved I will close that PR and apply the changes when merging.
These changes should not be applied for 2.5 and master.
=> EZP-31189: Reduce memory required for 1.7 and 1.13 branches to install

.env
Looks like the solution from https://github.com/ezsystems/ezplatform/pull/482 was working a week ago, but in the meantime Composer starting demanding even more memory 😞 See https://travis-ci.org/ezsystems/ezplatform/builds/620130994?utm_source=slack&utm_medium=notification
Increasing the memory limit should do the trick.
=> [Travis] Increased Composer memory limit for install

behat.yml.dist
JIRA: https://jira.ez.no/browse/EZEE-2928
**TO DO:** Remove TMP commit before merge
In most (if not all) jobs we're running tests with SYMFONY_DEBUG (or APP_DEBUG) set to true:
https://github.com/ezsystems/ezplatform/blob/2.5/.travis.yml#L13
https://github.com/ezsystems/ezplatform/blob/master/.travis.yml#L13
https://github.com/ezsystems/ezplatform-admin-ui/blob/1.5/.travis.yml#L10
https://github.com/ezsystems/ezplatform-admin-ui/blob/master/.travis.yml#L10
https://github.com/ezsystems/ezplatform-page-builder/blob/1.3/.travis.yml#L13
https://github.com/ezsystems/ezplatform-page-builder/blob/master/.travis.yml#L13
https://github.com/ezsystems/ezplatform-form-builder/blob/1.2/.travis.yml#L10
https://github.com/ezsystems/ezplatform-form-builder/blob/master/.travis.yml#L10 …
=> EZEE-2928: [Behat] Changed debug value to true for Symfony2Extention

composer.json
Adding conflict of doctrine/persistance because our product fails to install with:
```
Script eZ\Bundle\EzPublishCoreBundle\Composer\ScriptHandler::clearCache handling the symfony-scripts event terminated with an exception
[RuntimeException]
An error occurred when executing the "'cache:clear --no-warmup'" command:
Fatal error: Uncaught Symfony\Component\Debug\Exception\FatalThrowableError: Type error: Argument 1 passed to Doctrine\ORM\Configuration::s
etMetadataDriverImpl() must be an instance of Doctrine\Common\Persistence\Mapping\Driver\MappingDriver, instance of Doctrine\Persistence\Ma
pping\Driver\MappingDriverChain given, called in /Users/mareknocon/Desktop/repos/test_install/ezplatform/var/cache/dev/ContainerP9f9gat/get
Doctrine_Orm_DefaultEntityManagerService.php on line 25 in …
```
=> [Composer] Added doctrine/persistence conflict

app/config/config.yml, app/config/default_parameters.yml, app/config/env/platformsh.php
| **JIRA issue**     | [EZP-31377](https://jira.ez.no/browse/EZP-31377)
| **Target version** | `2.5`
| **Tests pass**     | N/A
| **Doc needed**     | no
GD uses PHP memory and hence it's better if we can use imagick if it's available to avoid risking running into php memory issues on larger images.
**TODO**:
=> EZP-31377: Use imagick by default on Platform.sh to avoid memory issues

.platform/services.yaml, composer.json
Doctrine version handling for Maria DB was fixed in https://github.com/platformsh/symfonyflex-bridge/releases/tag/2.2.0. And it lets to use `10.4` without any errors/issues.
=> [Platform.sh] Updated Maria DB version to 10.4

README.md
As `composer.json` https://github.com/ezsystems/ezplatform/blob/master/composer.json#L14 states eZ Platform 3.0 requires PHP in version 7.3 or higher, which should be reflected in `README.md` file.
=> Updated required PHP version to 7.3

doc/docker/base-dev.yml, doc/docker/base-prod.yml
JIRA: https://jira.ez.no/browse/EZP-31313
Related PRs:
https://github.com/ezsystems/ezpublish-kernel/pull/2933
https://github.com/ezsystems/BehatBundle/pull/124
Passing the env allowing to control SiteAccess used by Behat to Docker containers.
Before merging:
=> EZP-31313: Make Behat SiteAccess aware

templates/themes/standard/full/welcome_page.html.twig
> JIRA: https://jira.ez.no/browse/EZP-31518
https://github.com/ezsystems/ezplatform/pull/515 follow up . Removed "(" from eZ Platform discuss link.
=> Fixed incorrect link to discuss.ezplatform.com

doc/apache2/vhost.2.2.template, doc/apache2/vhost.template, doc/nginx/ez_params.d/ez_rewrite_params, web/app.php
> JIRA: https://jira.ez.no/browse/EZP-31519
I've changed the rule in `vhost.template` files in order to unify logic in both places. This way we can block some requests on httpd level.
Rejection logic has been moved to: https://github.com/ezsystems/ezpublish-kernel/pull/3010
=> EZP-31519: Moved app.php rejection snippet from front controller to ezpublish-kernel

upgrade/db/mysql/ezplatform-2.5.latest-to-3.0.0.sql, upgrade/db/postgresql/ezplatform-2.5.latest-to-3.0.0.sql
Required by: ezsystems/ezplatform-kernel#31
This PR introduces database upgrade scripts to migrate from eZ Platform 2.5 to 3.0.0.
Usually those scripts were placed in `ezpublish-kernel` package, but with package name and versioning change, it might be to confusing. The new way is to place it in here in the meta repository.
Moreover `ezsite_data` will now contain `ezplatform-release` key.
=> Prepared database upgrade scripts for eZ Platform 3.0.0

bin/console
> JIRA: https://jira.ez.no/browse/EZP-31535
Replated deprecated `Symfony\Component\Debug\Debug` class by `Symfony\Component\ErrorHandler\Debug` in `bin/console.php`. 
See https://github.com/symfony/symfony/blob/master/UPGRADE-5.0.md#debug
=> EZP-31535: Replated deprecated Symfony\Component\Debug\Debug class 

config/packages/ezplatform.yaml
This may be a minor forgotten non-updated misleading comment. 'http' is a value that can't be used anymore. It triggers the error "No driver found being able to handle purge_type 'http'."
During migration from v2.5.9 to v3.0.0-rc.1, I replace it with 'varnish' which seems OK.
=> Update comments about HttpCache purge type

bin/vhost.sh, doc/apache2/vhost.template, doc/docker/base-dev.yml, doc/docker/base-prod.yml, doc/docker/distribution.yml, doc/docker/my-ez-app-stack.yml, doc/docker/varnish.yml, doc/nginx/vhost.template
The environment variable used to control reverse proxy IP addresses in Symfony 5 is called `TRUSTED_PROXIES`:
https://symfony.com/doc/current/deployment/proxies.html
This is also the variable we use in `index.php:
https://github.com/ezsystems/ezplatform/blob/master/public/index.php#L16
Yet we are still using in some places (Docker setup, webserver config templates) APP_TRUSTED_PROXIES, which can lead to configuration issues.
=> Changed APP_TRUSTED_PROXIES variable to TRUSTED_PROXIES

.env, config/packages/cache_pool/cache.redis.yaml
As a Developer, I want to be able to change Redis cache namespace using env variables: https://jira.ez.no/browse/EZP-31541
=> EZP-31541: Redis cache namespace is pulled from env variables

behat.yml.dist, composer.json
JIRA: https://jira.ez.no/browse/EZP-31550
The 2.1 release in `bex/behat-screenshot` adds support for Symfony 5:
https://github.com/elvetemedve/behat-screenshot/releases/tag/2.1.0
This PR:
1) adds the `bex/behat-screenshot` (also sorts existing packages, what we should be doing)
2) enables screenshot config again
Tested locally, it works as it used to:
```
Screenshot has been taken. Open image at https://res.cloudinary.com/ezplatformtravis/image/upload/v1586340203/screenshots/5e8da15a67d8d189055721-vendor_ezsystems_ezplatform-admin-ui_features_standard_authentication_feature_4_d4amv5.png
```
=> EZP-31550: [Behat] Added screenshot extensions

doc/docker/redis.yml
https://jira.ez.no/browse/EZP-31541
followup to: https://github.com/ezsystems/ezplatform/pull/527
=> EZP-31541: Added new CACHE_NAMESPACE env to redis docker stack

.env
[parameters.yml disappeared in Symfony 4 and environment variables seem recommanded.](http://fabien.potencier.org/symfony4-best-practices.html)
Maybe it's more an [application configuration](https://symfony.com/doc/5.0/best_practices.html#use-parameters-for-application-configuration) than an [environment variable](https://symfony.com/doc/5.0/best_practices.html#use-environment-variables-for-infrastructure-configuration) and the comment could be just updated to something like `# set here for BC reasons, change them in services.yaml`
=> .env: Remove comment about parameters.yml

doc/docker/install-dependencies.yml
JIRA: https://jira.ez.no/browse/EZP-31579
Currently the `install-dependencies` container relies on PHP_IMAGE_DEV env variable.
For me this is confusing and leads to errors - it's not enough to specify PHP_IMAGE, but PHP_IMAGE_DEV is required.
Example error:
https://github.com/ezsystems/ezplatform-http-cache/blob/1.0/.travis.yml#L26 - only PHP_IMAGE is specified, but PHP_IMAGE_DEV is not.
This fails on Travis: https://travis-ci.org/github/ezsystems/ezplatform-http-cache/jobs/674863009
because the packages are installed using PHP 7.3, but tests are run using PHP7.1.
To avoid this confusion I think install-dependencies should rely on PHP_IMAGE variable.
=> [Docker] Changed install-dependencies to rely on PHP_IMAGE variable

.platform.app.yaml
As additional debuging for https://github.com/ezsystems/ezplatform-http-cache/pull/129, shown `TRUST_REMOTE` is no longer handled by front controller, in a way it was done in 2.5.
in 2.5 `app.php` there was following piece of code, which is now missing in 3.0.
```php
if ($trustedProxies = getenv('SYMFONY_TRUSTED_PROXIES')) {
if ($trustedProxies === 'TRUST_REMOTE') {
Request::setTrustedProxies([$request->server->get('REMOTE_ADDR')], Request::HEADER_X_FORWARDED_ALL);
} else {
Request::setTrustedProxies(explode(',', $trustedProxies), Request::HEADER_X_FORWARDED_ALL);
}
}
```
but, as we dont want to add stuff to index.php in termx of `flex` complaiance (correct me if I am wrong @webhdx) I think above logic can be handled in Symfony Request object itself, as since symfony 4.4, there is …
=> EZP-31603: Replaced TRUST_REMOTE with REMOTE_ADDR

.env, behat.yml.dist
JIRA: https://jira.ez.no/browse/EZP-31549
We have started getting invalid argument: 'id' can not be string errors, while testing the newest selenium image (20200326). Solution to this problem was adding a new line in behat.yml.dist ChromeOptions (w3c: false).
It is a known problem and it seems its not yet fixed for Mink - ref.
1. https://medium.com/@alex.designworks/chromedriver-75-enforces-w3c-standard-breaking-behat-tests-460cad435545
2. minkphp/MinkSelenium2Driver#293
Potential solution - php-webdriver/php-webdriver#560
=> [BEHAT] Updated selenium container to 20200326 version

.travis.yml
https://jira.ez.no/browse/EZP-31613
Regenerated Slack integration after workspace name change.
Also I've removed the notifications from the other workspace - it never became popular/used.
=> [Travis] Changed notifications token.

config/packages/buzz.yaml, config/packages/cache_pool/cache.memcached.yaml, config/packages/cache_pool/cache.redis.yaml, config/packages/cache_pool/cache.tagaware.filesystem.yaml, config/packages/ezplatform_http_cache.yaml, config/packages/graphql.yaml
Use 4 spaces indention (per Symfony coding standards).
Switch from "sequence on a new line" to "sequence on the same line".
=> consistent formatting for yaml

.platform.app.yaml
Add recommended configs from 
https://symfony.com/doc/current/performance.html 
https://docs.platform.sh/languages/php.html#opcache-preloading
Let me know if we should stay with PHP 7.3 and I'll remove the `opcache.preload` part.
=> platformsh performance tweeks

composer.json
Framework bundle 5.1.0 has a change incompatible with our code: https://github.com/symfony/symfony/issues/37042
We need to wait until it's fixed, so I'm adding a conflict with that version (hoping that it will be fixed in 5.1.1).
=> [Composer] Added conflict with symfony/framework-bundle 5.1.0

bin/.travis/trusty/update_docker.sh
We have builds failing with:
```
> Install DB and dependencies
/usr/local/bin/docker-compose: line 1: syntax error near unexpected token `newline'
/usr/local/bin/docker-compose: line 1: `<html>'
home/travis/.travis/functions: line 109: cd: /home/travis/build/ezplatform: No such file or directory
/usr/local/bin/docker-compose: line 1: syntax error near unexpected token `newline'
/usr/local/bin/docker-compose: line 1: `<html>'
```
Example failure: https://travis-ci.org/github/ezsystems/ezplatform/jobs/689872600
Mu current guess is that the command
```
curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
```
sometimes returns an HTML error page instead of an application, which cause us to use an HTML page …
=> [Travis] Check if downloaded docker-compose is an application

config/packages/overrides/platformsh.php
We are working on eZ Platform v3 upgrade on a Platform.sh environment. And we are using Varnish. Platform.sh environment we are using for has enabled HTTP Access control. Which means we get 401 response code when Varnish cache is purged. It happened more than once, and we decided to share our solution:
1. Setup `HTTPCACHE_USERNAME` and `HTTPCACHE_PASSWORD` variables in Platform.sh environment, which will store HTTTP Access control credentials:
```
PSH_ENV=ezplatform3ee
HTTP_ACCESS_USER=user
HTTP_ACCESS_PASSWORD=password
platform variable:create --level=environment --environment=${PSH_ENV} --name=HTTPCACHE_USERNAME --value=${HTTP_ACCESS_USER} --json=false --sensitive=false --prefix=env --visible-build=true --visible-runtime=true --enabled=true --inheritable=false
platform variable:create …
```
=> Platform.sh: allow to use HTTP access credentials for Varnish

composer.json
The config in meta we have right now:
https://github.com/ezsystems/ezplatform/blob/master/config/packages/doctrine_migrations.yaml
is meant for doctrine/doctrine-migrations-bundle ^2.0 and is not compatible with the 3.0 version released yesterday. This metarepo fails to finish `composer install` with:
```
Executing script cache:clear [KO]
[KO]
Script cache:clear returned with error code 1
!!
!!  In ArrayNode.php line 320:
!!
!!    Unrecognized options "dir_name, namespace" under "doctrine_migrations". Ava
!!    ilable options are "all_or_nothing", "check_database_platform", "connection
!!    ", "custom_template", "em", "factories", "migrations", "migrations_paths",
!!    "organize_migrations", "services", "storage".
!!
```
Adding a direct requirement for …
=> [Composer] Added direct requirement for doctrine/doctrine-migrations-bundle

composer.json
`symfony/flex` updated to `^1.7` (it was `^1.6` before).
=> Flex switched to 1.7

src/Kernel.php
There is a slack discussion in #ez-launchpad.
But I prefer to open that PR to the community.
Without this, there is no way to tell Docker to save the Symfony cache in the container rather than in the host.
On Mac OS this is a performance killer.
On 2.5 we still have it, why has it been removed?
https://github.com/ezsystems/ezplatform/blob/2.5/app/AppKernel.php#L84
Thanks!
=> Bring back SYMFONY_TMP_DIR (in another form) for Docker optimization

composer.json
Release v1.7.0 in fastest fixed the issue with queue order:
https://github.com/liuggio/fastest/releases/tag/v1.7.0
https://github.com/liuggio/fastest/issues/135
for which we have a workaround in BehatBundle:
https://github.com/ezsystems/BehatBundle/blob/7.0/bin/ezbehat#L57
But the new version (with the fix) is available only for PHP7.2 or higher, meaning that we can't use it in all jobs running tests on v2 (the lowest supported version is 7.1). Since our workaround cannot support both fastest versions at the same time (one will have invalid behaviour) we need to decide on one, in this case a version supported by the lowest version possible on v2 - hence ~1.6.0 requirement.
This requirement is valid only for 2.5 branch, in 3.0 and master it's not needed.
Tests are run in incorrect order, …
=> [Behat] Limited fastest version to ~1.6

doc/docker/install-dependencies.yml
Detected when working on: https://github.com/ezsystems/docker-php/pull/52 , which uses the `doc/docker/install-dependencies.yml -f doc/docker/install-database.yml` Dockerfiles.
Looks like the `DATABASE_VERSION` variable is not passed to the install_dependencies container, resulting in:
```
install_dependencies_1  | 
install_dependencies_1  | Checking database is up, attempt: 1
install_dependencies_1  | Ok: Connection succeeded to mysql 'ezp'.
install_dependencies_1  | > @php bin/console ezplatform:install clean
install_dependencies_1  | Creating database ezp if it does not exist, using doctrine:database:create --if-not-exists
install_dependencies_1  | 
install_dependencies_1  | In DBALException.php line 81:
install_dependencies_1  | …
```
=> [Docker] Added DATABASE_VERSION variable to install-dependencies

.env, doc/docker/Dockerfile-app, doc/docker/Dockerfile-distribution, doc/docker/Dockerfile-nginx, doc/docker/base-dev.yml, doc/docker/install-dependencies.yml
Removing the hardcoded `-node` and `-dev` variants to that our builds will keep working after https://github.com/ezsystems/docker-php/pull/52 is merged (and the build in https://github.com/ezsystems/docker-php/pull/52 can pass)
Once the above PR is merged I'll prepare another PR to this repo to switch to Docker v2 images.
=> [Docker] Removed hardcoded -node and -dev image usages

.travis.yml
Failing build: https://travis-ci.org/github/ezsystems/ezplatform/jobs/714344080 after https://github.com/ezsystems/ezplatform/pull/588
Needs to be adapted for 3.0, 3.1 and master to `ezsystems/php:7.3-v1-dev`
=> [Travis] Specified PHP_IMAGE_DEV for 7.1 job

.env, .travis.yml, doc/docker/README.md, doc/docker/base-dev.yml, doc/docker/db-postgresql.yml, doc/docker/import-dataset.yml, doc/docker/install-dependencies.yml
JIRA: https://jira.ez.no/browse/EZP-31620
This PR is the result of work done recently in docker-php, mostly https://github.com/ezsystems/docker-php/pull/52.
I have:
- switched the default PHP_IMAGE to `ezsystems/php:7.4-v2-node10` and dropped `PHP_IMAGE_DEV`, it's no longer used in our Docker stack
- added `ENABLE_XDEBUG` and `XDEBUG_CONFIG` variables to base-dev and base-prod (which should make  https://github.com/ezsystems/ezplatform/pull/587 not needed anymore - xdebug is present in all images now)
- added a new PostgreSQL Docker service
- added a job running Behat tests on PostgreSQL (requires https://github.com/ezsystems/ezplatform-admin-ui/pull/1445 to pass)
Passing PostgreSQL build: https://travis-ci.org/github/ezsystems/ezplatform/builds/715567661
=> [Docker] Switched image format and added PostgreSQL service

.platform/services.yaml
Changing the default version of Solr used on Platform.sh to 7.7.
The current Solr instruction for Platform.sh states:
```
```
But it's not working out of the box, because the `generate-config` script does not support Solr 6.6: https://github.com/ezsystems/ezplatform-solr-search-engine/blob/3.0/bin/generate-solr-config.sh#L31 (which is the version used by default).
After changing to 7.7 everything works as expected.
7.7 is the recommended version to use with solr-bundle 3.0: https://github.com/ezsystems/ezplatform-solr-search-engine/blob/3.0/README.md
and is supported by Platform.sh: https://docs.platform.sh/configuration/services/solr.html
The only issue I see here could be related to upgrades - people upgrading from v2 to v3 will have to adapt their config manually (and refer to …
=> [Platform.sh] Changed default version of Solr to 7.7

config/packages/dfs/dfs.yaml, config/packages/overrides/generic.php, config/packages/overrides/platformsh.php
| Question                                  | Answer
| ---------------------------------------- | ------------------
| **JIRA issue**                          | [EZP-31738](https://jira.ez.no/browse/EZP-31738), [EZP-31739](https://jira.ez.no/browse/EZP-31739), [EZP-31740](https://jira.ez.no/browse/EZP-31740).
| **Requires**                        | ezsystems/ezplatform-kernel#108
| **Type**                                   | bug
| **Target eZ Platform version** | `v3.1`+
| **BC breaks**                          | yes
| **Doc needed**                       | yes
This PR fixes DFS configuration and adjusts it for Symfony 5 changes.
There's no way to fix configuration in a BC-safe way due to changes between Symfony 3 and 5.
Required configuration is as follows
```bash …
```
=> EZP-31740: Fixed and migrated DFS configuration to Symfony 5

config/packages/webpack_encore.yaml
JIRA: [EZP-31982](https://jira.ez.no/browse/EZP-31982)
This in practice disables Encore built-in cache on dev environments, following Symfony's default configuration in this matter.
Fixes an issue when adding new entrypoints to webpack.config.js that were not recognized until cache was cleared - which lead
to confusing errors occuring in template files that included those entrypoints.
=> EZP-31982: Revert cache setting in Encore config to default

config/packages/cache_pool/cache.memcached.yaml, config/packages/cache_pool/cache.tagaware.filesystem.yaml
Fixes `cache_namespace` parameters to be in sync with Redis config.
=> Fix cache_namespace parameters for memcached and filesystem cache

composer.json
> JIRA: -
Added conflict with doctrine/dbal >= 2.11.0 to unblock CI on 1.13 branch:
```
install_app_1_1a889336cc0b | > Incenteev\ParameterHandler\ScriptHandler::buildParameters
install_app_1_1a889336cc0b | Creating the "app/config/parameters.yml" file
install_app_1_1a889336cc0b | > Sensio\Bundle\DistributionBundle\Composer\ScriptHandler::buildBootstrap
install_app_1_1a889336cc0b | > eZ\Bundle\EzPublishCoreBundle\Composer\ScriptHandler::clearCache
install_app_1_1a889336cc0b | 
install_app_1_1a889336cc0b |                                                         
install_app_1_1a889336cc0b |   [Symfony\Component\Console\Exception\LogicException]  
install_app_1_1a889336cc0b |   An option named "connection" already exists.          
install_app_1_1a889336cc0b | …
```
=> Added conflict with doctrine/dbal >= 2.11.0

doc/apache2/vhost.template, doc/nginx/vhost.template
Since eZ Platform 3 on Symfony 5, if `APP_ENV` is omitted from VHost, .env and .env.local, default environment is `dev`.
In https://github.com/ezsystems/ezplatform/blob/v3.1.3/config/bootstrap.php, when APP_ENV is undefined or null:
- if Dotenv is used, Dotenv will set APP_END to 'dev' in https://github.com/symfony/dotenv/blob/v5.1.6/Dotenv.php#L109 ;
- if Dotenv isn't used, the bootstrap will set it to dev at line 19.
Tested using Apache on
- eZ Platform EE 2.5.14 where default is prod;
- eZ Platform EE 3.1.3 where default is dev.
=> vhost.template: Update default APP_ENV from prod to dev

composer.json
https://jira.ez.no/browse/EZP-31821
For all supported branches.
There have been repeated requests for the security checker not to break the installation process. If we accept the premise that the checker should not lead to errors, but should still run and display packages with vulnerabilites, then this is a simple way to do it. This shows the output from `composer install && echo "SUCCESS!"` in v1.13 (and v2.5).
In v3.x Symfony scripts are run in a different way, and if we apply the same fix there it will not show the output from security-checker, just a green OK. If we're not going to fork the relevant Symfony repo, and if there's no easy way to overload it, then we have to go back to the old way of running security checker. And that requires moving it out from the `auto-scripts` …
=> EZP-31821: Failing security-checker results in errored installation

composer.json
**JIRA**: [EZP-31930](https://jira.ez.no/browse/EZP-31930)
**Target version**: 2.5.x, 3.1.x, 3.2
---
This is yet another attempt like ezsystems/ezpublish-kernel#2593 to fix the output of `ezplatform:install` Symfony command piped through Composer (`composer ezplatform-install`).
The issue is visible e.g. [here](https://travis-ci.org/github/ezsystems/ezplatform/jobs/728930873#L1072-L1078) or locally.
Seems it looks better when `bin/console` has `--ansi` option. TBD if this solves the issue for all platforms.
See **TODO** list.
=> EZP-31930: Improved output of `composer ezplatform-install` command

doc/docker/varnish.yml
JIRA: https://jira.ez.no/browse/EZP-31804
A potential replacement to the solution proposed in https://github.com/ezsystems/docker-php/pull/34
Currently we set `varnish` as trusted proxy, but it doesn't work - Symfony does not resolve hostnames when looking at trusted proxies, meaning that in our Docker stack no proxy is trusted. This makes it impossible to purge cache correctly when using it.
Things I've considered:
Currently `varnish` has a dependency on `app` (because it resolves the `app` hostname in `--acl-add` command, so adding a `varnish` dependency to `app` to resolve trusted proxy would create a circular dependency.
This leaves as with a possibility to wait until `varnish` container is available as in https://github.com/ezsystems/docker-php/pull/34 or we could try to set the IP …
=> EZP-31804: [Docker] Added fixed IP to varnish container to workaround TRUSTED_PROXIES setting

composer.json
Reopening previously approved https://github.com/ezsystems/ezplatform/pull/608 for QA, as it was merged too soon and reverted. See description and screenshot there.
This applies to 1.13 and 2.5.
For 3.1+ see https://github.com/ezsystems/ezplatform/pull/612
=> EZP-31821: Failing security-checker results in errored installation (1.13)

doc/docker/entrypoint/varnish/entrypoint.sh, doc/docker/entrypoint/varnish/parameters.vcl, doc/docker/varnish.yml
JIRA: https://issues.ibexa.co/browse/EZP-32103
Added the possibility to add entries to the debuggers list in the Varnish VCL and added the `app` container to the list.
This is needed by https://github.com/ezsystems/ezplatform-http-cache/pull/138 , where I want to rely on the X-Cache: MISS/HIT header for tests.
=> [Docker] EZP-32103: Added app container to varnish debuggers 

behat.yml.dist, config/packages/behat/doctrine.yaml, config/packages/behat/ezplatform.yaml, config/packages/behat/framework.yaml, config/packages/behat/routing.yaml
JIRA: https://issues.ibexa.co/browse/EZP-32103
~~Contains https://github.com/ezsystems/ezplatform/pull/623 and temp changes, needs rebase before merging.~~
Things done:
1) I've removed the default config from FriendsOfBehat\SymfonyExtension
We're using the default values for the kernel class and path. The env and debug value is taken from the loaded bootstrap file, which loads environmental variables - there's no change in behaviour if APP_ENV=behat, APP_DEBUG=1 is specified (which we do in all our builds) and it's not harcoded there in case someone wants to change it.
2) I've adjusted `behat` env configuration to be more prod-like: right now it contains all the files from `prod` env, reasoning: our tests should be running in a similar env as the production one (but with Debug enabled, so …
=> [Tests] EZP-32103: Adjusted Behat config to behave more like prod

bin/console
> JIRA: https://issues.ibexa.co/browse/EZP-31594
This is complementary PR to https://github.com/ezsystems/ezplatform-kernel/pull/145 which removes custom `Application` class handling `--siteaccess` option. It's no longer needed because the option is now handled by CompilerPass and EventListener.
=> EZP-31594: Replaced bin/console with original file from symfony/console recipe

composer.json
Follow up to https://github.com/ezsystems/ezplatform/pull/634
Build for PRs in BehatBundle are failing, example: https://travis-ci.com/github/ezsystems/BehatBundle/builds/209558836
This is fixed by this PR, proof: https://travis-ci.com/github/ezsystems/BehatBundle/builds/209568228 (used in TMP commit: https://github.com/ezsystems/BehatBundle/pull/168/commits/612265bce0883b7a317a7301e10cb20b1ce539f7 )
=> [Composer] Use branch alias for behatbundle

config/packages/ezplatform_admin_ui.yaml
This configuration is obsolete. The correct one is in `\EzSystems\EzPlatformAdminUiBundle\DependencyInjection\EzPlatformAdminUiExtension::prependJMSTranslation`
=> Removed obsolete configuration of translation

.platform.app.yaml
EZP-32254: [platform.sh] http cache purge type disabled during deploy
https://issues.ibexa.co/browse/EZP-32254
=> EZP-32254: [platform.sh] http cache purge type disabled during deploy

bin/.travis/trusty/setup_ezplatform.sh
JIRA: https://issues.ibexa.co/browse/EZP-32270
Docker Hub introduces rate limiting when downloading images. From https://www.docker.com/blog/docker-hub-image-retention-policy-delayed-and-subscription-updates/ :
```
Anonymous free users will be limited to 100 pulls per six hours, and authenticated free users will be limited to 200 pulls per six hours. 
```
This makes our build fail from time to time with:
```
(selenium/standalone-chrome-debug:3.141.59-20200326)...
3.141.59-20200326: Pulling from selenium/standalone-chrome-debug
stable: Pulling from library/nginx
ERROR: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit
```
(from …
=> [Travis] Added logging into Docker Hub

composer.json
For: 1.13, 2.5, 3.1, 3.2
https://issues.ibexa.co/browse/EZP-32289
Sensiolabs security-checker will stop working at the end of January 2021. https://github.com/sensiolabs/security-checker
There are ways of keeping the functionality, but they will need testing to avoid the issue of reports breaking installations, which we fixed earlier in the current solution. So for now we can remove it, and add the new variant later.
=> EZP-32289: Remove obsoleted security-checker

bin/.travis/trusty/setup_ezplatform.sh
We have builds failing with errors like:
```
Switched to a new branch 'tmp_76f9e4b'
/home/travis/build/ezplatform
> Make composer use tested dependency local checkout tmp_76f9e4b of ezplatform-workflow
> Require ezsystems/ezplatform-workflow:dev-tmp_76f9e4b as 1.1.x-dev
[RuntimeException]                                                           
Failed to read package information from /var/www/ezplatform-workflow as the  
path does not exist   
```
Link: https://travis-ci.com/github/ezsystems/ezplatform-admin-ui/builds/218066131
Root cause:
The issue is caused by these lines: https://github.com/ezsystems/ezplatform/blob/master/bin/.travis/trusty/setup_ezplatform.sh#L56-L80
We move the directory containg tested package to another location:
Code:
```
BASE_PACKAGE_NAME=`basename …
```
=> [Travis] Created the local dependency directory on host for Composer command to pass

bin/.travis/trusty/setup_ezplatform.sh
Example failure:
https://travis-ci.com/github/ezsystems/ezplatform-http-cache/jobs/486034188
Error:
```
---> ec18ce700090
Step 6/10 : COPY vendor/ezsystems/ezplatform-http-cache/docs/varnish/vcl/varnish5.vcl /etc/varnish/default.vcl
Service 'varnish' failed to build: COPY failed: stat /var/lib/docker/tmp/docker-builder696197820/var/www/ezplatform-http-cache/docs/varnish/vcl/varnish5.vcl: no such file or directory
```
Varnish container fails to builds, because it's not able to find the `vendor/ezsystems/ezplatform-http-cache/docs/varnish/vcl/varnish5.vcl` file.
This happens only for builds in ezplatform-http-cache repository and is caused by https://github.com/ezsystems/ezplatform/pull/648 .
In https://github.com/ezsystems/ezplatform/pull/648 I've changed the repository type to `path`. …
=> [Travis] Disabled symlinking of local dependency

composer.json
Failing build:
https://travis-ci.com/github/ezsystems/ezplatform/builds/229620437
Error:
```
Compile Error: Could not check compatibility between Symfony\Bridge\ProxyMa  
nager\LazyProxy\PhpDumper\LazyLoadingValueHolderGenerator::generate(Reflect  
ionClass $originalClass, Zend\Code\Generator\ClassGenerator $classGenerator  
) and ProxyManager\ProxyGenerator\LazyLoadingValueHolderGenerator::generate  
(ReflectionClass $originalClass, Laminas\Code\Generator\ClassGenerator $cla  
ssGenerator), because class Zend\Code\Generator\ClassGenerator is not avail  
able    
```
Steps to reproduce:
`composer create-project ezsystems/ezplatform:^2.5@dev`
I've used PHP 7.4 and suspect that not all supported PHP versions are affects (see green build on PHP 7.1 in …
=> [Composer] Added conflict with laminas/laminas-code:4.4.0

composer.json
Travis failure: https://travis-ci.com/github/ezsystems/ezplatform-page-builder/jobs/518410065#L2576
```
Executing script cache:clear [KO]
[KO]
Script cache:clear returned with error code 255
!!  PHP Fatal error:  Class EzSystems\EzPlatformPageBuilder\Security\EditorialMode\TokenManager contains 1 abstract method and must therefore be declared abstract or implement the remaining methods (Lexik\Bundle\JWTAuthenticationBundle\Services\JWTTokenManagerInterface::decodeFromJsonWebToken) in /var/www/vendor/ezsystems/ezplatform-page-builder/src/lib/Security/EditorialMode/TokenManager.php on line 24
!!  Symfony\Component\ErrorHandler\Error\FatalError {#10767
!!    -error: array:4 [
!!      "type" => 1
!!      "message" => "Class EzSystems\EzPlatformPageBuilder\Security\EditorialMode\TokenManager …
```
=> [Composer] Added conflict with lexik/jwt-authentication-bundle 2.12.0

.github/workflows/release_tag.yml
[IBX-656](https://issues.ibexa.co/browse/IBX-656)
Updated changelog generator, so that it properly sorts versions in a JSON object.
```shell
cat <<EOF | jq -r '.versions | sort_by( ltrimstr("v") | split(".") | map(tonumber) )'
{
"versions": [
"v2.5.99",
"v2.5.9",
"v2.5.10"
]
}
EOF
[
"v2.5.9",
"v2.5.10",
"v2.5.99"
]
```
=> IBX-656: Updated changelog generator's JQ oneliner
